import { Prisma } from "@prisma/client";

export const scrapedScholarships: Prisma.ScholarshipCreateInput[] = [
`;
const fs = require("fs");
const entries = fs.readFileSync("E:\\scholarship-project\\prisma\\scraped_entries.txt", "utf-8");
const content = fs.readFileSync("E:\\scholarship-project\\prisma\\generate_scraped_ts.js", "utf-8");
// Fix: This was generated by the previous script. Let me take a different approach.

// Actually, let me just modify the seed.ts to import and use the scraped data
