/**
 * TASK 2E — Priority Scholarships 2026–2027 (import-ready dataset).
 *
 * Source of truth: PRIORITY_SCHOLARSHIPS_2026.md (researched 2026-08-09 from
 * official sources only — government, agency, university and programme sites).
 *
 * Compatibility notes (see scripts/lib/scholarship-data.mjs / FIELD_DEFS):
 *  - `nameEn` is the identity key; records below reuse the existing curated
 *    nameEn where the same flagship already exists in prisma/seed.ts so the
 *    fill-empty import merge matches (never creates duplicates).
 *  - `source` uses the existing taxonomy value "MANUAL".
 *  - `benefits`/`requirements` follow the seed convention: JSON.stringify().
 *  - `isVerified` / `verifiedAt` / `isActive` / `applicationOpenDate` exist in
 *    the Prisma model but are NOT in FIELD_DEFS, so a current import pipeline
 *    drops them (they survive a direct Prisma upsert). See the TASK 2E report.
 *  - "2026–2027" = the application round opening late 2026 / early 2027 for
 *    intake 2027 (some programmes call that round "2027/2028").
 *  - A deadline is set ONLY where an official source published it; otherwise
 *    it is null and the published cycle facts live in `requirements`.
 */

export interface PriorityScholarshipRecord {
  nameEn: string;
  nameAr: string;
  country: string;
  university: string | null;
  degree: string;
  deadline: Date | null;
  flagUrl: string | null;
  description: string;
  benefits: string;
  requirements: string;
  eligibleCountries: string[];
  eligibleEducation: string[];
  fieldOfStudy: string[];
  minimumAge: number | null;
  maximumAge: number | null;
  minimumGPA: number | null;
  englishRequirement: string | null;
  requiresResearch: boolean;
  requiresWorkExp: boolean;
  applicationFee: number | null;
  competitionLevel: string;
  requiredDocuments: string[];
  sourceUrl: string;
  source: string;
  applicationOpenDate: Date | null;
  isVerified: boolean;
  verifiedAt: Date;
  isActive: boolean;
}

export const priorityScholarships2026: PriorityScholarshipRecord[] = [
  {
    nameEn: "Russian Government Quota Scholarship (Rossotrudnichestvo)",
    nameAr: "منحة الحكومة الروسية",
    country: "Russia",
    university: "500+ participating Russian universities (741 in the previous cycle)",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2027-01-15T23:59:00Z"),
    flagUrl: "/images/flags/russia.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "NOT_REQUIRED",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: [
      "PASSPORT",
      "TRANSCRIPT",
      "MEDICAL_CERTIFICATE",
      "MOTIVATION_LETTER",
      "RECOMMENDATION_LETTER",
      "PORTFOLIO",
    ],
    description:
      "Quota of the Government of the Russian Federation, administered by Rossotrudnichestvo through the 'Education in Russia' system — full tuition, monthly stipend and subsidised dormitory for students from 180+ countries at 500+ Russian universities.",
    benefits: JSON.stringify({
      tuition: "Full tuition fee for the whole study cycle",
      allowance: "Monthly state stipend (maintenance allowance)",
      housing: "Subsidised dormitory accommodation (2,500–3,769 RUB/month)",
      language: "Free 1-year Russian preparatory course",
      other: "Selection legal basis: Minobrnauki Order No. 1378 of 3 Nov 2020",
      notCovered: "Travel to/from Russia, health insurance and living costs are not covered",
    }),
    requirements: JSON.stringify({
      nationality:
        "Open to foreign citizens from 180+ countries; dual citizens (incl. Russian) only if permanently residing abroad and holding no Russian-issued diploma; must not already be enrolled in a Russian university",
      education: "Completed education appropriate to the level (secondary school for Bachelor, Bachelor's for Master's, Master's for PhD)",
      selection: "Competitive two-stage selection; up to 6 university choices (max 2 in Moscow, 2 in St. Petersburg)",
      documents: [
        "Passport",
        "Diploma + transcripts (translated, notarised/apostilled)",
        "Medical certificate",
        "HIV test",
        "Motivation letter",
        "Achievements/awards",
        "Recommendation letters",
        "Portfolio (arts)",
      ],
      deadline:
        "Dec 15 2026 for CIS countries; Jan 15 2027 for all other countries — per NUST MISIS official page; exact dates vary by country, confirm with the local Russian House/embassy",
      results: "Results ~Apr–May 2027",
      language: "No English test required — 1-year free Russian preparatory course provided",
      warning: "Apply only via education-in-russia.com; it is free — never pay an agent",
    }),
    sourceUrl: "https://education-in-russia.com/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Chevening Scholarship (UK Government)",
    nameAr: "منحة Chevening البريطانية",
    country: "United Kingdom",
    university: "Any eligible UK university (all Chevening-partner institutions)",
    degree: "Master",
    deadline: new Date("2026-10-06T11:00:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency required (to be met by the July following application)",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["ESSAY", "CV", "RECOMMENDATION_LETTER"],
    description:
      "The UK Government's global scholarship for future leaders — full tuition, monthly stipend, economy return flights and visa costs for a one-year taught master's at any UK university.",
    benefits: JSON.stringify({
      tuition: "Full tuition fees (MBA capped at £22,000 tuition contribution)",
      allowance: "Monthly stipend (London / non-London rates)",
      travel: "Economy return flights",
      housing: "Arrival and departure allowances",
      visa: "UK visa costs",
      other: "Up to £75 TB-test contribution; access to the global Chevening alumni network",
    }),
    requirements: JSON.stringify({
      nationality:
        "Citizen of a Chevening-eligible country/territory (160+); must return to your home country for 2 years after the award",
      education: "2:1-equivalent bachelor's degree",
      experience: "At least 2,800 hours (2 years) of work experience after the degree (paid, unpaid or voluntary)",
      leadership: "Leadership and networking potential",
      language: "English requirement met by the July following application",
      courses: "Choose 3 UK master's courses in the application",
      other: "No upper age limit; no UK Government-funded study in the UK before",
    }),
    sourceUrl: "https://www.chevening.org/scholarships/",
    source: "MANUAL",
    applicationOpenDate: new Date("2026-08-04T11:00:00Z"),
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Commonwealth Scholarships (UK)",
    nameAr: "منحة الكومنولث البريطانية",
    country: "United Kingdom",
    university: "Any participating UK university",
    degree: "Master / PhD",
    deadline: new Date("2026-10-20T15:00:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: [],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "NOT_REQUIRED",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["TRANSCRIPT", "RECOMMENDATION_LETTER"],
    description:
      "FCDO-funded Commonwealth Master's and PhD Scholarships (CSCUK) — full funding for Commonwealth citizens to study at any UK university, with a development-impact focus.",
    benefits: JSON.stringify({
      tuition: "Full tuition fees",
      allowance: "Monthly stipend of £1,712 (£2,000 London)",
      travel: "Approved return airfare + study travel grant",
      research: "PhD fieldwork allowance and mid-term airfare",
      family: "Family allowances",
      other: "No IELTS required by CSC",
      notCovered: "Dependant fares and extra living costs",
    }),
    requirements: JSON.stringify({
      nationality:
        "Master's — citizens/refugees of 42 eligible Commonwealth countries; PhD — 17 least-developed/vulnerable countries; full lists on the official site (Egypt is not listed for the Master's scheme)",
      residence: "Permanently resident in the eligible country",
      education: "First degree at least 2:1 (or 2:2 plus a postgraduate qualification); PhD applicants must not already be registered for a PhD/MPhil",
      availability: "Must be available to start in the UK in September 2027",
      nomination: "Must apply through a nominating agency — no direct applications; agencies have their own earlier internal deadlines",
      age: "No age limit",
      deadline: "20 Oct 2026, 16:00 BST (agency deadlines are earlier)",
    }),
    sourceUrl: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
    source: "MANUAL",
    applicationOpenDate: new Date("2026-09-08T00:00:00Z"),
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Swiss Government Excellence Scholarship",
    nameAr: "منحة الحكومة السويسرية",
    country: "Switzerland",
    university:
      "Swiss cantonal universities, ETH Zurich / EPFL, universities of applied sciences and research institutes",
    degree: "PhD / Research",
    deadline: null,
    flagUrl: "/images/flags/switzerland.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: 35,
    minimumGPA: null,
    englishRequirement: "English, German or French proficiency as required by the host institution and research plan",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: [
      "CV",
      "MOTIVATION_LETTER",
      "RESEARCH_PROPOSAL",
      "RECOMMENDATION_LETTER",
      "TRANSCRIPT",
      "PORTFOLIO",
    ],
    description:
      "Swiss Government Excellence Scholarships (FCS/ESKAS) fund research fellowships, PhD scholarships and art scholarships at Switzerland's leading institutions.",
    benefits: JSON.stringify({
      allowance: "Monthly stipend of CHF 2,450",
      insurance: "Health-insurance premiums covered (non-EU/EFTA)",
      housing: "CHF 600 rental-deposit grant",
      travel: "Half-Fare Travelcard + return-flight allowance (non-EU/EFTA)",
      other: "No tuition fees at Swiss public universities",
      notCovered: "Semester/tuition fees (~CHF 600–2,000 per semester) and family allowances",
    }),
    requirements: JSON.stringify({
      nationality: "183 countries with diplomatic relations to Switzerland (art scholarships: limited list)",
      age: "Born after 31 Dec 1991 (max 35)",
      education: "Master's completed by 31 Jul 2027 (ETHZ: 30 Jun 2027)",
      supervisor: "Mandatory letter of support from a Swiss academic supervisor",
      research: "Research plan required",
      exclusions: "Exclusions apply (prior ESKAS award, >3 attempts, >13 months residence in Switzerland)",
      deadline:
        "Per country of origin — officially published in the SBFI A–Z country list (dated 4 Aug 2026); no single global deadline",
      apply: "GO ESKAS portal (https://www.go.eskas.ch) opens 20 Aug 2026",
    }),
    sourceUrl: "https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships",
    source: "MANUAL",
    applicationOpenDate: new Date("2026-08-20T00:00:00Z"),
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Gates Cambridge Scholarship (UK)",
    nameAr: "منحة جيتس كامبريدج",
    country: "United Kingdom",
    university: "University of Cambridge",
    degree: "Master / PhD",
    deadline: new Date("2026-12-03T23:59:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency as required by Cambridge (typically IELTS 7.0–7.5)",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: [
      "RESEARCH_PROPOSAL",
      "PERSONAL_STATEMENT",
      "CV",
      "RECOMMENDATION_LETTER",
      "TRANSCRIPT",
    ],
    description:
      "A full-cost scholarship at the University of Cambridge founded by the Bill and Melinda Gates Foundation, covering the full cost of study for outstanding postgraduate students from any country outside the UK.",
    benefits: JSON.stringify({
      tuition: "Full Cambridge tuition (University Composition Fee)",
      allowance: "Maintenance allowance for the duration of study",
      travel: "One economy airfare each way",
      visa: "Approved visa costs + Immigration Health Surcharge",
      research: "Discretionary conference and fieldwork funding",
    }),
    requirements: JSON.stringify({
      nationality: "Citizens of any country outside the UK",
      education: "Admission to a Cambridge postgraduate programme required (PhD, MSc, MLitt, MPhil or one-year postgraduate course)",
      merit: "Intellectual ability, leadership, commitment to improving the lives of others",
      other: "Must not have studied at Cambridge before; no age limit",
      deadlines:
        "Round 1 (US citizens resident in the USA): 14 Oct 2026; Round 2 (all others): 3 Dec 2026",
      docs: "Cambridge postgraduate application + Gates Cambridge funding selection, 4 Gates questions, 2 academic references + 1 Gates reference",
    }),
    sourceUrl: "https://www.gatescambridge.org/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Rhodes Scholarship (Oxford)",
    nameAr: "منحة رودس — أوكسفورد",
    country: "United Kingdom",
    university: "University of Oxford",
    degree: "Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: [],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency as required by Oxford",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description:
      "The oldest and one of the most prestigious international scholarships, funding full-time postgraduate study (DPhil, MSc/MPhil, BCL/MJur) at the University of Oxford.",
    benefits: JSON.stringify({
      tuition: "All University and College fees",
      allowance: "Annual stipend (£19,092 cited for 2026/27)",
      travel: "One economy flight home → Oxford and one back",
      other: "Financial means ignored in selection",
    }),
    requirements: JSON.stringify({
      nationality:
        "Eligibility via Rhodes constituencies (countries/groups/territories); the Global constituency is currently not accepting applications — use the official eligibility checker",
      age: "Generally 18–24 on 1 Oct of the application year (varies by constituency)",
      criteria: "Four selection criteria from Cecil Rhodes' Will: academic excellence, energy, leadership, moral force of character",
      deadlines:
        "USA constituency: 23:59 ET, 7 Oct 2026; other constituencies publish their own dates",
      docs: "Online form, education history + transcripts, proposed courses, CV, 5–8 referees, Academic Statement (≤450 words), Personal Statement; no application fee",
    }),
    sourceUrl: "https://rhodeshouse.ox.ac.uk/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Schwarzman Scholars (China)",
    nameAr: "منحة شوارزمان الصينية",
    country: "China",
    university: "Schwarzman College, Tsinghua University",
    degree: "Master",
    deadline: new Date("2026-09-09T19:00:00Z"),
    flagUrl: "/images/flags/china.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "TOEFL iBT 100 / IELTS 7 / Duolingo 130 / Cambridge 185 (unless native speaker or 2+ years in an English-medium degree)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["CV", "TRANSCRIPT", "ESSAY", "RECOMMENDATION_LETTER"],
    description:
      "A fully funded one-year Master's in Global Affairs at Tsinghua University's Schwarzman College, building a network of future leaders.",
    benefits: JSON.stringify({
      tuition: "Full tuition",
      fees: "Mandatory fees",
      housing: "Room and board",
      allowance: "Personal stipend + laptop/equipment subsidy",
      travel: "One-time round-trip travel stipend",
      insurance: "Health insurance",
    }),
    requirements: JSON.stringify({
      nationality:
        "Open to all; US/Global applicants must be non-Chinese citizens with a non-China passport (specific rules for those born in China); Chinese citizens use the separate China application",
      age: "18 and under 29 as of 1 Aug 2027",
      education: "Undergraduate degree conferred by 1 Aug 2027",
      language: "English proficiency unless native speaker or 2+ years in an English-medium degree",
      fields: "Leadership + global-affairs curriculum; no specific prior field required",
      deadline: "9 Sep 2026, 3:00 p.m. EDT — late applications not accepted",
      docs: "CV (≤2 pages), optional video, transcripts, up to 5 leadership roles/awards, Leadership Essay (750 words) + Statement of Purpose (500 words) + 2 short answers, 3 recommendations, originality certification (no AI-generated materials)",
    }),
    sourceUrl: "https://www.schwarzmanscholars.org/",
    source: "MANUAL",
    applicationOpenDate: new Date("2026-04-08T00:00:00Z"),
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Knight-Hennessy Scholars (Stanford)",
    nameAr: "منحة نايت-هينسي — ستانفورد",
    country: "United States",
    university: "Stanford University",
    degree: "Master / PhD",
    deadline: new Date("2026-10-06T20:00:00Z"),
    flagUrl: "/images/flags/usa.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency as required by Stanford's graduate programmes",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["CV", "ESSAY", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description:
      "Stanford's flagship graduate scholarship funding up to 3 years of any full-time Stanford graduate degree — MS/MA, PhD, JD, MD, MBA and more.",
    benefits: JSON.stringify({
      tuition: "Tuition + associated fees",
      allowance: "Stipend for living and academic expenses",
      travel: "One-time travel stipend",
      insurance: "Health insurance",
      other: "One-time academic enrichment grant",
      notFunded: "Family-member costs",
    }),
    requirements: JSON.stringify({
      nationality: "All nationalities; no age limit",
      education: "Must apply to AND enroll in a full-time Stanford graduate programme (concurrent application)",
      criteria: "Excellence, purpose-driven leadership, civic-mindedness",
      deadline:
        "6 Oct 2026, 1:00 p.m. PT — apply by whichever is earlier: the KHS deadline or the department's Stanford deadline",
      docs: "Resume, 3 short answers (≤300 words), personal essay (≤1,400 words), 2 recommendation letters (3rd optional), transcripts, video statement (≤2 min), plus the separate Stanford programme application",
    }),
    sourceUrl: "https://knight-hennessy.stanford.edu/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "KAUST Fellowship (Saudi Arabia)",
    nameAr: "منحة كاوست — جامعة الملك عبدالله",
    country: "Saudi Arabia",
    university: "King Abdullah University of Science and Technology (KAUST)",
    degree: "Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/saudi-arabia.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: [
      "Engineering",
      "Computer Science",
      "Biology",
      "Physics",
      "Mathematics",
      "Chemistry",
      "Environmental Science",
    ],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5 / TOEFL iBT 81 / PTE 62 / Cambridge 176",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: [
      "TRANSCRIPT",
      "CV",
      "MOTIVATION_LETTER",
      "RECOMMENDATION_LETTER",
      "LANGUAGE_TEST",
      "PASSPORT",
    ],
    description:
      "The KAUST Fellowship is awarded automatically to all admitted graduate students — full tuition, generous monthly stipend, on-campus housing and health insurance in a world-class STEM research environment.",
    benefits: JSON.stringify({
      tuition: "Full tuition + bench fee (up to ~USD 35k/yr)",
      allowance: "Monthly stipend (~USD 20k/yr M.S.; USD 25–30k/yr Ph.D.)",
      housing: "On-campus housing",
      insurance: "Health insurance",
      relocation: "Relocation support",
      other: "Total package ~USD 70–80k/yr",
    }),
    requirements: JSON.stringify({
      nationality: "All nationalities",
      education: "Bachelor's (M.S.) / Master's (Ph.D.)",
      age: "≥18; normally ≤30 (M.S.) / ≤35 (Ph.D.)",
      gpa: "GPA ≥ 3.0/4.0 (competitive)",
      language: "IELTS 6.5 / TOEFL iBT 81 / PTE 62 / Cambridge 176; GRE optional",
      fields: "STEM disciplines offered at KAUST",
      deadline:
        "2027-entry closing dates not yet published; applications open mid-August 2026; KAUST runs semester-based windows (Fall/Spring), not rolling",
      docs: "Transcripts (certified translation), CV, statement of purpose (~750 words), 3 referees, English test score, passport/ID copy",
    }),
    sourceUrl: "https://admissions.kaust.edu.sa/fees-funding",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Manaaki New Zealand Scholarships",
    nameAr: "منحة ماناكي النيوزيلندية",
    country: "New Zealand",
    university: "Participating New Zealand institutions (plus two Pacific universities in Fiji for eligible Pacific citizens)",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/new-zealand.svg",
    eligibleCountries: [
      "Cambodia",
      "Indonesia",
      "Lao PDR",
      "Malaysia",
      "Nepal",
      "Philippines",
      "Thailand",
      "Timor-Leste",
      "Viet Nam",
    ],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English per institution (IELTS 6.5 postgraduate / 6.0 undergraduate guidance)",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["TRANSCRIPT"],
    description:
      "New Zealand Government (MFAT) scholarships covering full tuition and a living allowance for study in New Zealand — restricted to Pacific and Asia regions for tertiary study since 9 Aug 2026.",
    benefits: JSON.stringify({
      tuition: "Full tuition fees",
      allowance: "Living allowance + establishment allowance",
      travel: "Return travel + travel insurance",
      trips: "Trips home for longer programmes",
      other: "Medical insurance + reintegration allowance",
      notCovered: "Accommodation (self-arranged)",
    }),
    requirements: JSON.stringify({
      nationality:
        "Official regions for tertiary study are now Pacific and Asia only — Africa and Latin America are not listed; Asia: Cambodia, Indonesia, Lao PDR, Malaysia, Nepal, Philippines, Thailand, Timor-Leste (undergraduate only), Viet Nam",
      age: "≥18 (Samoa Foundation 17+); applicants under 40 preferred",
      residence: "2 years' residency in your home country",
      experience: "≥1 year full-time work experience (postgraduate courses)",
      fields: "Restricted to officially recommended subjects per country",
      commitment: "2-year home-country development commitment",
      deadline:
        "Main tertiary round not yet announced. Samoa Foundation sub-scheme: midday 4 Sep 2026 (NZ time) — currently open",
      docs: "Transcripts (with grading scale); on shortlist: verified translations, certificates, English scores, ID",
    }),
    sourceUrl: "https://www.nzscholarships.govt.nz/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Turkiye Burslari Scholarship (Türkiye)",
    nameAr: "منحة تركيا بورسلاري",
    country: "Turkey",
    university: "Participating Turkish universities (60+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/turkey.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "NOT_REQUIRED",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["PASSPORT", "TRANSCRIPT", "RESEARCH_PROPOSAL"],
    description:
      "Türkiye Bursları (YTB) is a fully funded Turkish government scholarship covering tuition, university placement, monthly stipend, accommodation and health insurance, plus a free one-year Turkish course.",
    benefits: JSON.stringify({
      tuition: "Full tuition + university placement",
      allowance: "Monthly stipend: 4,500 TL (associate/bachelor), 6,500 TL (master's), 9,000 TL (PhD)",
      housing: "Dorm fees (undergraduate) / housing allowance (master's & PhD)",
      language: "1-year free Turkish course",
      travel: "One-off flight ticket",
      insurance: "Health insurance",
    }),
    requirements: JSON.stringify({
      nationality:
        "All countries; ineligible: Turkish citizens / persons who lost Turkish citizenship, and those currently enrolled at a Turkish university at the same level",
      academic: "Minimum 70% (associate/bachelor), 75% (graduate), 90% (health programmes)",
      age: "Under 21 (associate/bachelor), under 30 (master's), under 35 (PhD), under 50 (research)",
      selection: "Merit + interview selection",
      fields: "Broad range across all disciplines",
      deadline:
        "2027-intake dates not yet published (past cycle: 10 Jan – 20 Feb 2026); annual Jan–Feb window per the official calendar",
      docs: "ID/passport, photo, diplomas, transcripts, national/international exam results, language tests if required, research proposal (PhD)",
    }),
    sourceUrl: "https://www.turkiyeburslari.gov.tr/en/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "DAAD EPOS Scholarship (Development-Related Postgraduate Courses)",
    nameAr: "منحة DAAD EPOS الألمانية",
    country: "Germany",
    university: "Participating German universities offering EPOS courses",
    degree: "Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/germany.svg",
    eligibleCountries: [],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: [
      "Economics",
      "Engineering",
      "Regional & Urban Planning",
      "Agriculture & Forestry",
      "Natural & Environmental Sciences",
      "Medicine & Public Health",
      "Social Sciences",
      "Education",
      "Law",
      "Media",
    ],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English per course; German B1 minimum at application for German-taught courses",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["CV", "MOTIVATION_LETTER", "TRANSCRIPT", "RECOMMENDATION_LETTER"],
    description:
      "DAAD's Development-Related Postgraduate Courses (EPOS, funded by BMZ) fund students from developing countries on master's and exceptional doctoral courses in Germany.",
    benefits: JSON.stringify({
      allowance: "Monthly 992 EUR (graduates) / 1,300 EUR (doctoral; 1,400 from Feb 2026)",
      insurance: "Health, accident and liability insurance",
      travel: "Travel allowance",
      housing: "Possible rent and family allowances",
    }),
    requirements: JSON.stringify({
      nationality:
        "Graduates from developing/newly industrialised countries (DAAD eligibility list; ~150+ countries incl. all of the Arab region); not eligible if resident in Germany for >15 months at the deadline",
      education: "Bachelor's with above-average results (upper third); degrees normally ≤6 years old",
      experience: "≥2 years of relevant professional experience after the bachelor's",
      language: "English per course; German B1 minimum at application for German-taught courses",
      fields:
        "Development-related EPOS courses: economics/business, engineering, regional/urban planning, agriculture/forestry, natural & environmental sciences, medicine/public health, social sciences/education/law, media",
      deadline:
        "Course-specific and officially published in the DAAD intake 2027/2028 deadline list (e.g. 15 Oct 2026 for Freiburg MSc Env. Governance); apply directly to each course, max 3 ranked",
      docs: "DAAD application form, Europass CV, motivation letter, employer recommendation (letterhead/signature/stamp), employment certificates, language proofs, degree + transcript copies (certified translations), APS certificate (China applicants)",
    }),
    sourceUrl: "https://www.daad.de/en/information-services-for-higher-education-institutions/further-information-on-daad-programmes/epos/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Erasmus Mundus Joint Master Degree",
    nameAr: "منحة إيراسموس موندوس",
    country: "Multiple (Europe)",
    university: "Consortium of European universities (≥3 institutions in ≥3 countries, ≥2 EU)",
    degree: "Master",
    deadline: null,
    flagUrl: "/images/flags/eu.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: [
      "Engineering",
      "Computer Science",
      "Environmental Science",
      "Life Sciences",
      "Health",
      "Economics",
      "Social Sciences",
      "Law",
      "Physics",
      "Mathematics",
      "Arts",
    ],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English per consortium (typically IELTS 6.5–7.0)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT", "RECOMMENDATION_LETTER"],
    description:
      "Erasmus Mundus Joint Masters (Erasmus+ KA2, managed by EACEA) — study at 2+ European universities in different countries, earning a joint or double master's degree with full scholarship.",
    benefits: JSON.stringify({
      tuition: "Participation costs (tuition) covered",
      allowance: "Up to €1,400/month for up to 24 months, contributing to travel, visa, installation and living costs",
      regional: "Additional NDICI/IPA regional scholarships for some regions",
      other: "Not every listed master funds scholarships",
    }),
    requirements: JSON.stringify({
      nationality: "Open worldwide (consortia keep geographical balance; ≤10% of scholarships to one nationality)",
      education: "Bachelor's degree (or in final year, graduating before programme start)",
      fields:
        "~220 funded programmes across engineering/IT, environment, life sciences, health, economics, social sciences, law, physics, math, art",
      deadline:
        "No central deadline — each consortium publishes its own for the 2027 intake (general window Oct–Jan); apply directly to each consortium via the Erasmus Mundus Catalogue",
      docs: "Per consortium (typically form, CV, motivation letter, degrees/transcripts, language proof, references)",
    }),
    sourceUrl: "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "MEXT Scholarship (Japanese Government Scholarship)",
    nameAr: "منحة MEXT اليابانية",
    country: "Japan",
    university: "Various Japanese universities",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/japan.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English or Japanese proficiency depending on programme",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: [
      "RESEARCH_PROPOSAL",
      "TRANSCRIPT",
      "RECOMMENDATION_LETTER",
      "MEDICAL_CERTIFICATE",
      "PASSPORT",
    ],
    description:
      "The Japanese Government (MEXT) Scholarship — Embassy Recommendation track for research students (master's/doctoral) and undergraduates — covering tuition, monthly stipend and round-trip airfare.",
    benefits: JSON.stringify({
      allowance:
        "Monthly stipend: ¥143,000 (research, non-degree) → ¥144,000 (master's) / ¥145,000 (doctoral); ¥117,000 (undergraduate)",
      tuition: "Tuition and entrance fees at national universities",
      travel: "Round-trip economy airfare",
    }),
    requirements: JSON.stringify({
      nationality:
        "Countries with diplomatic relations with Japan; apply via the Japanese embassy/consulate in your home country (per-embassy quotas)",
      education: "Research: bachelor's / 16 years of schooling by grant start; undergraduate: 12 years of schooling + age criteria",
      age: "Research: born on or after 2 Apr 1992 (FY2027 guidelines)",
      selection: "Embassy screening + university entrance exams",
      deadline:
        "No single global deadline — each embassy sets its own window; FY2028 deadlines not yet published (FY2027 round closed May–Jul 2026)",
      docs: "Application form, field-of-study/research plan, transcripts, graduation certificates, recommendation letters, medical certificate (prescribed form), language certificates, passport copy",
    }),
    sourceUrl: "https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Chinese Government Scholarship (CSC)",
    nameAr: "منحة الحكومة الصينية",
    country: "China",
    university: "Participating Chinese universities (280+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/china.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "HSK for Chinese-taught programmes or IELTS/TOEFL for English-taught",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["TRANSCRIPT", "RECOMMENDATION_LETTER", "PASSPORT", "MEDICAL_CERTIFICATE"],
    description:
      "The Chinese Government Scholarship (Type A — Bilateral Programme) via the China Scholarship Council funds full-time study at Chinese universities — tuition, accommodation, monthly stipend and insurance.",
    benefits: JSON.stringify({
      tuition: "Full tuition fees",
      housing: "On-campus accommodation (or subsidy)",
      allowance: "Monthly stipend: CNY 2,500 (bachelor), CNY 3,000 (master's), CNY 3,500 (doctoral)",
      insurance: "Comprehensive medical insurance",
      travel: "International airfare (Type A)",
    }),
    requirements: JSON.stringify({
      nationality:
        "All countries except PRC citizens; Bilateral Programme applies via the Chinese embassy in your home country (agency number required)",
      age: "Under 25 (bachelor), under 35 (master's), under 40 (doctoral)",
      education: "Full-time degree programmes within the dispatching authority's quota",
      language:
        "HSK for Chinese-taught or IELTS/TOEFL for English-taught; CSCA score report now mandatory for bachelor's applicants",
      deadline:
        "2027/2028 call not published as of 9 Aug 2026; per-embassy deadlines, no global date",
      docs: "CSC online application (with agency number), notarised diploma + transcripts, study plan, 2 recommendation letters (master's/doctoral), passport copy, Foreigner Physical Examination Form, language certificates, art portfolio where applicable",
    }),
    sourceUrl: "http://www.campuschina.org",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fulbright Foreign Student Program (USA)",
    nameAr: "منحة فولبرايت الأمريكية",
    country: "United States",
    university: "Various US universities",
    degree: "Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/usa.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "TOEFL iBT or IELTS (country-specific requirements)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: [
      "PERSONAL_STATEMENT",
      "CV",
      "RECOMMENDATION_LETTER",
      "TRANSCRIPT",
      "LANGUAGE_TEST",
    ],
    description:
      "The flagship US Government international exchange program offering full funding — J-1 visa sponsorship, airfare, tuition, monthly stipend and insurance — for master's and doctoral study.",
    benefits: JSON.stringify({
      visa: "J-1 visa sponsorship",
      travel: "Round-trip airfare",
      tuition: "Tuition + required fees",
      allowance: "Monthly living stipend",
      insurance: "Health and accident insurance",
    }),
    requirements: JSON.stringify({
      nationality:
        "Citizens of ~160 participating countries, each with its own Fulbright Commission / US Embassy competition; US citizens and dual US citizens ineligible",
      education: "Bachelor's completed before grant start",
      fields: "Almost all fields, excluding clinical medicine (limited exceptions such as public health); typically no MBA",
      deadline:
        "No single global deadline — each in-country commission/embassy sets its own; Fall-2028 deadlines not yet published",
      docs: "Online application, personal statement + study/research objectives, CV, transcripts, 2–3 recommendation letters, TOEFL/IELTS (and sometimes GRE), passport copy",
      selection: "Strong academic record, English proficiency, leadership potential; in-country interview for shortlisted candidates",
    }),
    sourceUrl: "https://foreign.fulbrightonline.org/about/foreign-student-program",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Stipendium Hungaricum Scholarship",
    nameAr: "منحة Stipendium Hungaricum",
    country: "Hungary",
    university: "Participating Hungarian universities (30+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/hungary.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English or Hungarian proficiency depending on the programme",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: [
      "MOTIVATION_LETTER",
      "TRANSCRIPT",
      "RECOMMENDATION_LETTER",
      "MEDICAL_CERTIFICATE",
      "PASSPORT",
    ],
    description:
      "The Hungarian State Scholarship (Tempus Public Foundation) — no tuition fee, monthly stipend, accommodation contribution and health-insurance contribution for students from 100+ partner countries.",
    benefits: JSON.stringify({
      tuition: "No tuition fee",
      allowance:
        "Monthly stipend: HUF 43,700 (bachelor/master/one-tier master/non-degree), HUF 140,000 (doctoral years 1–2) → 180,000 (year 3+)",
      housing: "HUF 40,000/month accommodation contribution",
      insurance: "HUF 65,000/year health-insurance contribution",
    }),
    requirements: JSON.stringify({
      nationality:
        "Nationals of 100+ sending partner countries (official partner list); apply via the sending partner + Tempus Public Foundation",
      education: "Meet the degree/age requirements of the target programme + host-institution admission requirements",
      language: "English or Hungarian proficiency depending on the programme",
      rules: "One-degree-per-level rules apply",
      deadline:
        "2027/2028 call not yet published; next application period starts November 2026 (past cycle closed 15 Jan 2026)",
      docs: "Online application, motivation letter, education certificates + transcripts, language certificate, medical certificate, passport copy; doctoral: research proposal + supervisor acceptance",
    }),
    sourceUrl: "https://stipendiumhungaricum.hu/apply/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Swedish Institute Scholarship for Global Professionals",
    nameAr: "منحة المعهد السويدي",
    country: "Sweden",
    university: "Participating Swedish universities",
    degree: "Master",
    deadline: null,
    flagUrl: "/images/flags/sweden.svg",
    eligibleCountries: ["Egypt", "Jordan", "Iraq", "Morocco", "Kenya", "Nigeria"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Governance", "Public Health", "Entrepreneurship & Innovation", "STEM"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency (per eligible programme; typically IELTS 6.5+)",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["CV", "RECOMMENDATION_LETTER", "PERSONAL_STATEMENT"],
    description:
      "The Swedish Institute Scholarship for Global Professionals (SISGP) fully funds tuition and a living allowance for English-taught master's programmes in Sweden — open to citizens of 34 countries including Egypt, Jordan and Iraq.",
    benefits: JSON.stringify({
      tuition: "Full tuition fees (paid to the university)",
      allowance: "Monthly living allowance of SEK 12,000",
      travel: "One-time travel grant of SEK 15,000 (SEK 10,000 for Armenia/Azerbaijan/Belarus/Georgia/Moldova/Ukraine)",
      network: "SI network membership",
      notCovered: "Insurance, family grants, and the University Admissions application fee (SEK 900)",
    }),
    requirements: JSON.stringify({
      nationality:
        "Citizens of 34 eligible SISGP countries (incl. Egypt, Jordan, Iraq, Morocco, Kenya, Nigeria — full list on si.se); 'Pioneering Women in STEM' is a separate 10-country scheme for female citizens",
      education: "Admitted/conditionally admitted to an eligible master's programme; liable to pay tuition fees + paid University Admissions fee",
      experience: "Work experience (≥3,000 hours for most countries) + leadership experience",
      language: "English proficiency per programme",
      exclusions:
        "Not currently a Swedish degree holder / previously SI-scholarshipped / Swedish, EU or EEA citizen (exceptions apply)",
      deadline: "2027/28 call not yet published (past cycle: SI portal 9–25 Feb 2026)",
      docs: "SI-template CV (≤3 pages), SI-template proof of work + leadership (signed/stamped), 2 reference letters (SI template, one work-based), passport/ID copy, motivation statement",
    }),
    sourceUrl: "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Australia Awards Scholarship",
    nameAr: "منحة جوائز أستراليا",
    country: "Australia",
    university: "Participating Australian universities",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/australia.svg",
    eligibleCountries: ["Egypt", "Morocco", "Algeria", "Iraq", "Jordan", "Palestine"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English per institution (typically IELTS 6.5)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["TRANSCRIPT", "RECOMMENDATION_LETTER", "LANGUAGE_TEST"],
    description:
      "DFAT's flagship Australia Awards Scholarships fund full-time study at Australian universities — full tuition, return airfare, a living-contribution stipend and support for students from participating countries.",
    benefits: JSON.stringify({
      tuition: "Full tuition fees",
      travel: "Return economy airfare",
      allowance: "Contribution to living expenses (fortnightly stipend)",
      other: "Once-off establishment allowance, initial visa costs, OSHC, Introductory Academic Program, academic/disability support",
    }),
    requirements: JSON.stringify({
      nationality:
        "Citizens of participating countries (Indo-Pacific + Africa; Africa incl. Egypt, Morocco, Algeria; MENA incl. Iraq, Jordan, Palestine); full country profiles on the DFAT site",
      education: "Meet the institution's academic and English requirements",
      commitment: "Leadership and development commitment; must return home for ≥2 years after the award",
      fields: "Development-aligned study; priority fields set per country",
      deadline:
        "2028-intake round not yet announced (past cycle: 2027 intake opened 1 Feb 2026, closed 30 Apr 2026 for most countries)",
      docs: "Application form (OASIS), transcripts, English test results, referee reports; Indonesia & Philippines use country portals",
    }),
    sourceUrl: "https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Government of Ireland International Education Scholarship (GOI-IES)",
    nameAr: "منحة الحكومة الأيرلندية",
    country: "Ireland",
    university: "Eligible Irish higher education institutions",
    degree: "Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/ireland.svg",
    eligibleCountries: [],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency as required by the host institution",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description:
      "The Government of Ireland International Education Scholarship (GOI-IES) awards a €10,000 stipend plus a full fee waiver for one year of full-time study (master's, postgraduate diploma or PhD) at an Irish HEI — 60 scholarships per year.",
    benefits: JSON.stringify({
      allowance: "€10,000 stipend for one year",
      tuition: "Full fee waiver from the host Irish HEI for that year",
      notCovered: "Funding is for one year only; no living/travel extras",
    }),
    requirements: JSON.stringify({
      nationality:
        "Domicile outside the EU/EEA, Switzerland and the UK (most non-EU/EEA citizens); Russian and Belarusian nationals not eligible",
      education: "Conditional or final offer of admission to an eligible Irish HEI at time of application",
      criteria: "Outstanding academic achievement, communication skills, extracurricular involvement, strong rationale",
      deadline:
        "2027 call not yet announced (past cycle: 2026 call opened 29 Jan 2026, closed 12 Mar 2026; outcomes early Jun 2026)",
      docs: "Proof of offer of admission, 2 references, online application form, supporting evidence",
    }),
    sourceUrl: "https://hea.ie/policy/internationalisation/goi-ies/",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Romanian Government Scholarship (MFA Scholarships for non-EU Students)",
    nameAr: "منحة الحكومة الرومانية",
    country: "Romania",
    university: "Accredited Romanian higher education institutions",
    degree: "Bachelor / Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/romania.svg",
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "NOT_REQUIRED",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["TRANSCRIPT", "PASSPORT", "CV", "RESEARCH_PROPOSAL"],
    description:
      "Romanian Government scholarships (MFA + Ministry of Education and Research, GD 288/1993) for non-EU citizens — full tuition for the study cycle, monthly scholarship, financed Romanian preparatory year and dormitory accommodation.",
    benefits: JSON.stringify({
      tuition:
        "Full tuition for the study cycle + exemption from application/registration fees and aptitude tests",
      allowance: "Monthly scholarship during the prep year and studies",
      language: "Financed Romanian-language preparatory year",
      housing: "Dormitory accommodation (subject to availability)",
      notCovered: "Visa costs, travel, medical-certificate costs, non-dormitory accommodation, dependants",
    }),
    requirements: JSON.stringify({
      nationality:
        "Citizens of all non-EU countries; exclusions: Romanian-origin citizens / Romanian historical communities, persons with Romanian protection, diplomats/IO staff, current Romanian-state scholarship holders",
      academic: "Last-graduated-school average ≥ 7/10 (Good); PhD requires a Doctoral Tutor's written agreement + admission interview",
      fields: "All fields except Medicine, Dental Medicine and Pharmacy (explicitly excluded)",
      language: "Romanian proficiency (or financed prep year); no English test for bachelor's/master's",
      deadline:
        "2027-intake round not yet announced (past cycle: 16 Feb – 31 Mar 2026; results ~15 Jul 2026)",
      docs: "Diplomas + transcripts with authorised translations (EN/FR/ES/RO), birth certificate (translated), passport copy (first 3 pages), CV (EN/FR/RO), PhD: letter of intent + research project + tutor agreement; apostilled (Hague) study documents; GDPR consent",
    }),
    sourceUrl: "https://www.mae.ro/en/node/10251",
    source: "MANUAL",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-09T00:00:00Z"),
    isActive: true,
  },
];
