/**
 * TASK 2F — Scholarship enrichment dataset (import-ready).
 *
 * Enriches 17 of the 26 top-ranked scraped scholarships (SCHOLARSHIP_
 * ENRICHMENT_PRIORITIES.csv, ranks 1–27 minus the Chevening curated overlap)
 * with verified official data. Every record matches an EXISTING scraped
 * scholarship by exact nameEn, so the fill-empty import merge UPDATES it —
 * never creates a duplicate. Run with --force so that only the small set of
 * deliberate corrections below overwrites existing values; everything else is
 * equal to the DB (skipped) or an empty gap field (filled).
 *
 * Enrichment scope per record:
 *  - gap fields filled (were null/empty): eligibleCountries, eligibleEducation,
 *    fieldOfStudy, minimumAge, maximumAge, minimumGPA, englishRequirement,
 *    requiresResearch, requiresWorkExp, applicationFee, requiredDocuments,
 *    benefits, requirements.
 *  - deliberate corrections (differ from the existing DB values — verified):
 *      degree  Gilman (was "Master", programme is undergraduate)  -> "Bachelor"
 *      degree  CQU (was "Bachelor / Master / PhD", RHD only)      -> "Master / PhD"
 *      degree  Siena (was "Master", covers undergrad too)         -> "Bachelor / Master"
 *      degree  Harvard MBA (was "Bachelor")                       -> "Master"
 *      degree  Slovakia NSP (no bachelor's stays)                 -> "Master / PhD"
 *      degree  USTC (also undergraduate)                          -> "Bachelor / Master / PhD"
 *      nameAr  NSHSS + Harvard MBA: replaced embedded "部分" mojibake with "جزئية"
 *      university Bradford "Bradford University " (trailing space) -> "University of Bradford"
 *      university Shanghai "Shanghai Government " (trailing space) -> "Shanghai Government Scholarship"
 *
 * NOT included (9 SKIP+FLAG records — unverified or poor fit; documented in
 * SCHOLARSHIP_ENRICHMENT_PRIORITIES.md / the Task 2F report):
 *   AI UK (rank 1, no matching official scholarship), Üsküdar (rank 4, mojibake
 *   name/URL), UoL Computer Science (rank 6, "fully funded" claim unverified),
 *   Florida Nursing (rank 15, US community-college), Altınbaş (rank 16, mojibake
 *   + generic claim), BeMo (rank 18, commercial), DAAD generic page (rank 20,
 *   mismatched description, duplicates curated DAAD), Catholic Foresters (rank 23,
 *   US members-only), KCC (rank 25, US community college, US residents).
 *
 * Compatibility notes (see scripts/lib/scholarship-data.mjs / FIELD_DEFS):
 *  - `nameEn` is the identity key — values below are copied verbatim from the DB.
 *  - `deadline` values are copied verbatim (incl. 23:59:00Z time component) so
 *    the merge treats them as equal and never rewrites them.
 *  - `source` stays "SCRAPED" (provenance preserved).
 *  - `description` and `flagUrl` are intentionally omitted → untouched by the
 *    merge; verified facts live in `benefits` / `requirements`.
 *  - `benefits`/`requirements` follow the seed convention: JSON.stringify().
 *  - `isVerified` / `verifiedAt` / `isActive` / `applicationOpenDate` are NOT in
 *    FIELD_DEFS, so the import pipeline drops them (they only survive a direct
 *    Prisma upsert). They are set here so the dataset tests can assert them.
 */

export interface ScholarshipEnrichmentRecord {
  nameEn: string;
  nameAr: string;
  country: string;
  university?: string | null;
  degree: string;
  deadline: Date;
  eligibleCountries: string[];
  eligibleEducation: string[];
  fieldOfStudy: string[];
  minimumAge: number | null;
  maximumAge: number | null;
  minimumGPA: number | null;
  englishRequirement: string | null;
  requiresResearch: boolean;
  requiresWorkExp: boolean;
  applicationFee: number | null;
  competitionLevel: string;
  requiredDocuments: string[];
  benefits: string;
  requirements: string;
  sourceUrl: string;
  source: string;
  applicationOpenDate: Date | null;
  isVerified: boolean;
  verifiedAt: Date;
  isActive: boolean;
}

export const scholarships: ScholarshipEnrichmentRecord[] = [
  {
    nameEn: "Master’s in Renewable and Sustainable Energy in the United Kingdom 2026",
    nameAr: "ماجستير في الطاقة المتجددة والمستدامة في المملكة المتحدة 2026",
    country: "United Kingdom",
    university: "University of Bradford",
    degree: "Master",
    deadline: new Date("2026-08-20T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Sustainable Energy Engineering",
      "Industrial Engineering",
      "Electronic Engineering",
      "Computer Engineering",
    ],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "IELTS 6.0 minimum (or equivalent) for the taught master's",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["TRANSCRIPT", "CV", "RECOMMENDATION_LETTER", "ENGLISH_TEST", "PASSPORT"],
    benefits: JSON.stringify({
      coverage: "Tuition-fee discount for international students on the MSc in Renewable and Sustainable Energy",
      scholarship: "Up to £7,500 (2026/27 international fee £19,500 → ~£12,000 for eligible students)",
      meroScholarship: "Separate MERO Scholarship worth £5,000 for applicants from MENA/South Asia regions",
      application: "Automatic consideration — no separate scholarship application",
      note: "Confirm current amounts on the official University of Bradford international scholarship page",
    }),
    requirements: JSON.stringify({
      degree: "2:1 honours degree (or equivalent) in an engineering discipline",
      english: "IELTS 6.0 minimum (or equivalent)",
      experience: "Minimum two years of industrial experience in an engineering field",
      intake: "September and January intakes",
      deadline: "Applications close 20 August 2026 (scraped date)",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-masters-scholarship-in-sustainable-energy-uk-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Partially Funded Master's Scholarship in UK From York University 2026",
    nameAr: "منحة دراسية للماجستير في المملكة المتحدة من جامعة يورك 2026",
    country: "United Kingdom",
    degree: "Master",
    deadline: new Date("2026-08-28T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Business Management"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "IELTS 6.5 (or equivalent) for taught postgraduate programmes",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["TRANSCRIPT", "CV", "RECOMMENDATION_LETTER", "ENGLISH_TEST", "PASSPORT"],
    benefits: JSON.stringify({
      coverage: "Partial tuition-fee discount for international students on eligible business-management master's programmes at York University (UK)",
      value: "Discount amount varies by programme — confirmed on the official University of York scholarships page",
      application: "Automatic consideration for eligible applicants (no separate form)",
    }),
    requirements: JSON.stringify({
      level: "Taught master's programme in business management",
      english: "IELTS 6.5 (or equivalent)",
      deadline: "Applications close 28 August 2026 (scraped date)",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/partially-funded-masters-scholarship-in-uk-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded Scholarships for Bachelor's, Master's, and PhD in Germany 2026",
    nameAr: "منح دراسية ممولة بالكامل لدرجات البكالوريوس والماجستير والدكتوراه في ألمانيا 2026",
    country: "Germany",
    degree: "Master / PhD",
    deadline: new Date("2026-09-01T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "German or English proficiency depending on the programme (German B1 minimum at application for German-taught courses)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT", "RECOMMENDATION_LETTER", "LANGUAGE_TEST"],
    benefits: JSON.stringify({
      coverage: "Monthly stipend for Master's and PhD studies at German universities (approx. €1,100–€1,350/month) plus allowances",
      tuition: "German public universities charge no tuition (small semester fee)",
      funding: "Funded by the German Federal Ministry of Education and Research (BMBF) and the Federal Foreign Office",
      note: "Scholarship is for graduate (Master's/PhD) applicants from DAC-list developing countries",
    }),
    requirements: JSON.stringify({
      nationality: "Students from DAC-list developing countries (Africa, Asia, Latin America, Middle East, Eastern Europe)",
      level: "Master's and PhD applicants (some programmes also admit undergraduates)",
      language: "German B1 minimum at application for German-taught; English proficiency for English-taught",
      deadlines: "Fall 2026 round: 15 Jul–1 Sep 2026 · Spring 2027 round: 15 Jan–1 Mar 2027",
      contact: "studienwerk@boell.de",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-scholarships-for-bachelors-masters-and-phd-in-germany-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "McCall MacBain Scholarship | Fully Funded Master's Programs at McGill University in Canada",
    nameAr: "منحة ماكول ماكباين | برامج ماجستير ممولة بالكامل في جامعة ماكجيل في كندا",
    country: "Canada",
    degree: "Master",
    deadline: new Date("2026-09-23T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency per McGill graduate admission requirements",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["TRANSCRIPT", "CV", "RECOMMENDATION_LETTER", "PERSONAL_STATEMENT"],
    benefits: JSON.stringify({
      tuition: "Full tuition and fees at McGill University",
      allowance: "Living stipend of CAD $2,000 per month during study",
      additional: "Health insurance, relocation allowance, mentorship and leadership development",
      location: "McGill University, Montreal, Canada",
    }),
    requirements: JSON.stringify({
      level: "First master's or professional degree at McGill University (any field)",
      eligibility: "Open to Canadian and international applicants; strong academic record and leadership potential",
      english: "English proficiency per McGill admission requirements",
      deadline: "Latest closing date 23 September 2026; international applicants typically apply earlier — confirm the exact round on mccallmacbain.org",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/mccall-macbain-scholarship-fully-funded-masters-programs-at-mcgill-university-in-canada",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded Undergraduate, Master’s & PhD Scholarship in China 2026",
    nameAr: "منحة دراسية ممولة بالكامل للبكالوريوس والماجستير والدكتوراه في الصين 2026",
    country: "China",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-09-30T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Science and Engineering", "Engineering", "Natural Sciences", "Computer Science"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency for English-taught programmes (IELTS/TOEFL); HSK for Chinese-taught",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["TRANSCRIPT", "PASSPORT", "CV", "ENGLISH_TEST"],
    benefits: JSON.stringify({
      tuition: "Full tuition-fee waiver",
      stipend: "Monthly stipend: 2,500 RMB (undergraduate), 3,000 RMB (master's), 3,500 RMB (PhD)",
      insurance: "Comprehensive health insurance",
      research: "Research funding for graduate students",
    }),
    requirements: JSON.stringify({
      level: "Undergraduate, master's and PhD programmes taught in English at USTC (science and engineering)",
      english: "English proficiency per programme (IELTS/TOEFL)",
      deadline: "30 September 2026 is the scraped listing date — the 2026 window is closed; the next cycle typically opens around October 2026, verify on the official USTC International College page",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-undergraduate-masters-phd-scholarship-in-china-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Study Opportunity in Europe at EMUNI University | Master’s and PhD with Partial Scholarships",
    nameAr: "فرصة دراسية في أوروبا في جامعة EMUNI | ماجستير ودكتوراه مع منح جزئية",
    country: "Slovenia",
    degree: "Master / PhD",
    deadline: new Date("2026-09-30T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Business", "Digital Law", "Environment", "Geopolitics"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency proof (programmes taught in English)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "TRANSCRIPT", "CV", "PASSPORT", "ENGLISH_TEST"],
    benefits: JSON.stringify({
      award: "EMUNI Scholarship Fund Partial Tuition Award — up to €2,500 for 2026/2027",
      slots: "Up to 15 first-year and 15 second-year students",
      note: "As announced 22 July 2026 the first-period funds are fully awarded; a second period will not open — check emuni.si for the next cycle",
    }),
    requirements: JSON.stringify({
      level: "Master's and PhD programmes at EMUNI University, Slovenia (English-taught: business, digital law, environment, geopolitics)",
      gpa: "GPA of at least 8/10 for first-year candidates",
      english: "English proficiency proof",
      application: "Apply via the 1ka.arnes.si link on the official call page",
      deadline: "30 September 2026 (scraped date); official 2026/27 funds were fully awarded in the first period — confirm current status on emuni.si",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/study-opportunity-in-europe-20262027-masters-and-phd-with-partial-scholarships",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded Scholarships in Iraq 2026 for International Students",
    nameAr: "منح دراسية ممولة بالكامل في العراق 2026 للطلاب الدوليين",
    country: "Iraq",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-09-30T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: [
      "Medicine",
      "Dentistry",
      "Pharmacy",
      "Engineering",
      "Artificial Intelligence",
      "Cybersecurity",
      "Business Administration",
      "Information Technology",
    ],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency per programme (teaching language may be Arabic or English)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["PASSPORT", "TRANSCRIPT", "CV"],
    benefits: JSON.stringify({
      funding: "Full or partial funding",
      coverage: "Tuition-fee waivers, university accommodation and health insurance",
      level: "Bachelor's, master's and PhD programmes at 78+ Iraqi public and private universities",
      platform: "Official application platform: studyiniraq.scrd-gate.gov.iq",
    }),
    requirements: JSON.stringify({
      level: "Undergraduate and postgraduate programmes at Iraqi public/private universities",
      english: "Per programme (Arabic or English teaching language)",
      deadline: "30 September 2026 (scraped); postgraduate rounds close earlier — verify on the official platform",
      note: "Government initiative of the Ministry of Higher Education and Scientific Research of Iraq (4th edition)",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-scholarships-in-iraq-2026-for-international-students",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Gilman International Scholarship 2026 | Fully Funded Program for Undergraduate Students in the USA",
    nameAr: "منحة جيلمان الدولية 2026 | برنامج ممول بالكامل للطلاب في المرحلة الجامعية في الولايات المتحدة الأمريكية",
    country: "United States",
    degree: "Bachelor",
    deadline: new Date("2026-10-01T23:59:00.000Z"),
    eligibleCountries: ["United States"],
    eligibleEducation: ["BACHELOR"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "NOT_REQUIRED",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["ESSAY", "TRANSCRIPT"],
    benefits: JSON.stringify({
      award: "Up to US$5,000 toward study or intern abroad; Critical Need Language Award up to US$8,000",
      programme: "U.S. Department of State programme administered through IIE",
      note: "For U.S. undergraduates studying or interning abroad",
    }),
    requirements: JSON.stringify({
      citizenship: "U.S. citizen or national",
      funding: "Must be receiving a Federal Pell Grant",
      level: "Undergraduate student studying or interning abroad",
      deadline: "1 October 2026, 11:59pm Pacific (Fall 2026 cycle)",
      cycles: "Annual cycles: October (fall) and March (spring) deadlines",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/gilman-international-scholarship-2026-fully-funded-program-for-undergraduate-students-in-the-usa",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "University of Winnipeg Scholarship 2026 in Canada for International Students with Funding up to CAD 5,000",
    nameAr: "منحة جامعة وينيبيغ 2026 في كندا للطلاب الدوليين بالتمويل حتى 5,000 دولار كندي",
    country: "Canada",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-10-01T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency per University of Winnipeg admission requirements",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    benefits: JSON.stringify({
      value: "CAD $5,000 one-time entrance award",
      eligibility: "International students entering their first year at the University of Winnipeg (undergraduate, graduate, collegiate or PACE)",
      selection: "Based on leadership potential, community involvement and academic excellence",
    }),
    requirements: JSON.stringify({
      english: "English proficiency per UWinnipeg admission requirements",
      application: "Apply through the UWinnipeg scholarship portal after admission",
      deadline: "1 October 2026 (Winter 2026/27 intake); the Fall intake deadline is 1 June each year",
      note: "Qualifying-year and Pre-Masters applicants are not eligible for the graduate award",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/university-of-winnipeg-scholarship-2026-in-canada-for-international-students-with-funding-up-to-cad-5000",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Partially Funded Bachelor's Scholarship in USA 2026",
    nameAr: "منحة دراسية جزئية للبكالوريوس في الولايات المتحدة الأمريكية 2026",
    country: "United States",
    degree: "Bachelor",
    deadline: new Date("2026-10-04T23:59:00.000Z"),
    eligibleCountries: ["United States"],
    eligibleEducation: ["BACHELOR"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: 18,
    minimumGPA: null,
    englishRequirement: "NOT_REQUIRED",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["ESSAY"],
    benefits: JSON.stringify({
      award: "US$1,000 (18 Under 18 Award of the National Society of High School Scholars)",
      recipients: "18 recipients",
      note: "Recognises achievement in community service, extracurricular activities or leadership",
    }),
    requirements: JSON.stringify({
      membership: "Must be an NSHSS member",
      residency: "U.S. resident",
      age: "Aged 18 or younger",
      level: "High school freshman–senior seeking a professional certificate, associate or bachelor's degree",
      submission: "30-second to 3-minute video/essay submission",
      deadline: "4 October 2026 (scraped date); the 2025–26 cycle closed 10 April 2026 — confirm the current cycle on nshss.org",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/partially-funded-bachelors-scholarship-in-usa-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "National Scholarship Program Slovakia 2026 for International Students",
    nameAr: "برنامج المنح الوطنية في سلوفاكيا 2026 لطلاب الدول الخارجية",
    country: "Slovakia",
    degree: "Master / PhD",
    deadline: new Date("2026-10-31T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "Language proficiency as required by the host institution (English or Slovak)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT", "RECOMMENDATION_LETTER", "LANGUAGE_TEST"],
    benefits: JSON.stringify({
      stipend: "Monthly scholarship €620–€1,050 depending on level and type of stay",
      allowance: "Travel allowance based on distance from the home country",
      note: "For study/research stays of master's students, PhD students, university teachers, researchers and artists",
    }),
    requirements: JSON.stringify({
      level: "Master's students (at least 2.5 years completed), PhD students, university teachers, researchers and artists",
      language: "Proficiency as required by the host institution",
      invitation: "An invitation from the Slovak host institution is required",
      deadline: "31 October 2026 at 16:00 CET",
      note: "Funded by the Ministry of Education, Research, Development and Youth of Slovakia; administered by SAIA",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/national-scholarship-program-of-the-slovak-republic",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Human Rights Scholarship 2026 at the University of Melbourne | Fully Funded Master’s & PhD in Australia",
    nameAr: "منحة حقوق الإنسان 2026 في جامعة ملبورن | ماجستير ودكتوراه ممولين بالكامل في أستراليا",
    country: "Australia",
    degree: "Master / PhD",
    deadline: new Date("2026-10-31T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Human Rights"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency per University of Melbourne graduate research admission",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["RESEARCH_PROPOSAL", "TRANSCRIPT", "CV", "RECOMMENDATION_LETTER"],
    benefits: JSON.stringify({
      feeRemission: "100% fee remission",
      allowance: "Living allowance $44,500 per year (2026 rate) for up to 2 years (Master by Research) or 3.5 years (PhD)",
      relocation: "Relocation grant of $2,000–$3,000 depending on distance",
      insurance: "OSHC single membership for international students",
      totalValue: "Total value approximately $89,000–$155,000",
    }),
    requirements: JSON.stringify({
      level: "Graduate research degree (Master by Research or PhD) in Human Rights at the University of Melbourne",
      english: "English proficiency per graduate research admission",
      eligibility: "Open to domestic and international students",
      deadline: "Applications close 31 October 2026",
      outcome: "Outcomes announced by email in February of the following year",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/human-rights-scholarship-2026-at-the-university-of-melbourne-fully-funded-masters-phd-in-australia",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded Research Scholarships at CQUniversity Australia",
    nameAr: "منحة أبحاث ممولة بالكامل في جامعة CQUniversity أستراليا",
    country: "Australia",
    degree: "Master / PhD",
    deadline: new Date("2026-12-30T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency per CQUniversity research degree admission",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["RESEARCH_PROPOSAL", "TRANSCRIPT", "CV", "RECOMMENDATION_LETTER"],
    benefits: JSON.stringify({
      stipend: "AUD $36,000 per annum (tax-exempt) for living expenses",
      duration: "Full research support for up to 3 years",
      note: "Funded by the Australian Government Research Training Program (RTP)",
    }),
    requirements: JSON.stringify({
      level: "Higher-degree-by-research candidature (Master by Research or PhD) at CQUniversity",
      english: "English proficiency per research degree admission",
      eligibility: "Open to domestic and international students",
      deadline: "31 December 2026 (scraped); candidature assessments close in rounds (April and September)",
      note: "No separate scholarship application — discuss a research topic with a supervisory team first",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-research-scholarships-at-cquniversity-australia",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded ADB Master's Scholarship in Asia and Pacific 2026",
    nameAr: "منحة ماجستير بنك التنمية الآسيوي الممولة بالكامل في آسيا والمحيط الهادئ 2026",
    country: "Japan",
    degree: "Master",
    deadline: new Date("2026-12-30T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Science and Technology", "Economics", "Business Administration", "Law", "Engineering"],
    minimumAge: null,
    maximumAge: 35,
    minimumGPA: null,
    englishRequirement: "Working knowledge of English required",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["TRANSCRIPT", "CV", "RECOMMENDATION_LETTER", "ENGLISH_TEST", "PASSPORT"],
    benefits: JSON.stringify({
      coverage: "Full tuition, monthly subsistence and housing allowances, books allowance, medical insurance and round-trip travel",
      note: "About 135 scholarships per year; administered by the Asian Development Bank and funded by the Government of Japan",
      programme: "Master's at designated institutions in Asia-Pacific",
    }),
    requirements: JSON.stringify({
      nationality: "National of an ADB borrowing member country that is also Japanese ODA-eligible; must not hold dual citizenship of a developed country",
      age: "Not more than 35 years old at the time of application",
      academic: "Bachelor's degree with a superior academic record",
      experience: "At least 2 years of full-time professional work experience after obtaining a bachelor's degree",
      english: "Working knowledge of English",
      return: "Must return to the home country for at least 2 years after completion",
      deadline: "Varies by institution (scraped listing: 30 December 2026) — check the designated university's own deadline",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-adb-masters-scholarship-in-asia-and-pacific-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded Shanghai Government Scholarship 2026 with Stipend & Accommodation",
    nameAr: "منحة حكومة شنغهاي الممولة بالكامل 2026 مع منحة ومسكن",
    country: "China",
    university: "Shanghai Government Scholarship",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2027-04-30T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "Chinese (HSK) or English proficiency depending on the programme language",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["TRANSCRIPT", "PASSPORT", "CV", "ENGLISH_TEST"],
    benefits: JSON.stringify({
      typeA: "Type A (Full): full tuition, on-campus accommodation (economic double room), monthly living allowance 2,500 RMB, off-campus allowance 700 RMB/month (with university approval), comprehensive medical insurance 800 RMB/year",
      typeB: "Type B (Partial): full tuition-fee exemption plus comprehensive medical insurance",
      note: "Funded by the Shanghai Municipal People's Government (programme established 2006)",
    }),
    requirements: JSON.stringify({
      level: "Undergraduate, master's and PhD programmes at universities in Shanghai",
      language: "Chinese proficiency (HSK) for Chinese-taught programmes or English proficiency for English-taught",
      deadline: "30 April 2027 (scraped); current-cycle applications typically close mid-April — verify on the chosen host university's page",
      application: "Apply directly to the host university in Shanghai",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-shanghai-government-scholarships-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Fully Funded Undergraduate and Master's Scholarships at University of Siena, Italy 2026",
    nameAr: "منح دراسية ممولة بالكامل للبكالوريوس والماجستير في جامعة سيينا في إيطاليا 2026",
    country: "Italy",
    degree: "Bachelor / Master",
    deadline: new Date("2027-05-06T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["BACHELOR", "MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency for English-taught programmes; Italian for Italian-taught",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["TRANSCRIPT", "PASSPORT", "CV", "ENGLISH_TEST"],
    benefits: JSON.stringify({
      excellence: "Siena International Excellence Scholarships for international students enrolling in selected English-taught master's programmes",
      dsu: "DSU Toscana regional scholarships/benefits for eligible students",
      note: "2026/27 DSU call: register on the DSU Toscana portal before 7 September 2026, 1:00pm (Italian time)",
    }),
    requirements: JSON.stringify({
      level: "Undergraduate and master's programmes at the University of Siena (foundation, bachelor's, master's and combined degrees)",
      english: "English proficiency for English-taught programmes",
      deadline: "6 May 2027 (scraped); the 2026/27 Excellence Scholarship call was published 5 May 2026 — verify the current cycle on unisi.it",
      application: "Apply via the university portal; obtain a Letter of Eligibility (pre-admission), then enrol",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/fully-funded-undergraduate-and-masters-scholarships-at-university-of-siena-italy-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
  {
    nameEn: "Partially Funded Harvard MBA Scholarship 2026",
    nameAr: "منحة ماجستير إدارة الأعمال في جامعة هارفارد جزئية 2026",
    country: "United States",
    degree: "Master",
    deadline: new Date("2027-05-31T23:59:00.000Z"),
    eligibleCountries: ["All"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Business Administration"],
    minimumAge: null,
    maximumAge: null,
    minimumGPA: null,
    englishRequirement: "English proficiency per Harvard Business School admission requirements",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["TRANSCRIPT", "CV", "RECOMMENDATION_LETTER", "ESSAY", "PERSONAL_STATEMENT"],
    benefits: JSON.stringify({
      coverage: "Partial funding toward the Harvard MBA tuition",
      internship: "Two-month unpaid internship at the Boustany Foundation office in Monaco (travel and accommodation covered)",
      frequency: "Awarded once per year",
      note: "Administered by the Boustany Foundation; deadline 31 May 2027",
    }),
    requirements: JSON.stringify({
      admission: "Must be granted admission to the Harvard Business School MBA programme",
      internship: "Mandatory two-month unpaid internship in Monaco",
      english: "English proficiency per HBS admission requirements",
      deadline: "31 May 2027",
      note: "Open to outstanding international students; confirm current nationality priorities on boustany-foundation.org",
    }),
    sourceUrl: "https://www.for9a.com/en/opportunity/partially-funded-harvard-mba-scholarship-2026",
    source: "SCRAPED",
    applicationOpenDate: null,
    isVerified: true,
    verifiedAt: new Date("2026-08-10T00:00:00Z"),
    isActive: true,
  },
];

export default scholarships;
