import { PrismaClient, Prisma } from "@prisma/client";
import { scrapedScholarships } from "./scraped-scholarships";
import {
  normalizeRecord,
  mergeScholarship,
  type ScholarshipLike,
} from "../scripts/lib/scholarship-data.mjs";

const prisma = new PrismaClient();

interface ScholarshipInput {
  nameEn: string;
  nameAr: string;
  country: string;
  university: string;
  degree: string;
  deadline: Date | null;
  flagUrl: string | null;
  description: string;
  benefits: string;
  requirements: string;
  eligibleCountries: string[];
  eligibleEducation: string[];
  fieldOfStudy: string[];
  minimumAge: number | null;
  maximumAge: number | null;
  minimumGPA: number | null;
  englishRequirement: string | null;
  requiresResearch: boolean;
  requiresWorkExp: boolean;
  applicationFee: number | null;
  competitionLevel: string;
  requiredDocuments: string[];
  sourceUrl: string;
  source: string;
}

const scholarships: ScholarshipInput[] = [
  {
    nameEn: "MEXT Scholarship (Japanese Government Scholarship)",
    nameAr: "منحة MEXT اليابانية",
    country: "Japan",
    university: "Various Japanese Universities",
    degree: "Master / PhD",
    deadline: new Date("2026-05-30T23:59:00Z"),
    flagUrl: "/images/flags/japan.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80 or IELTS 6.0",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["RESEARCH_PROPOSAL", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT", "MEDICAL_CERTIFICATE"],
    description: "A prestigious Japanese government scholarship covering full tuition, monthly allowance, and round-trip airfare for research students at top Japanese universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver", allowance: "Monthly allowance of approximately ¥143,000-¥145,000", travel: "Round-trip airfare to Japan", housing: "Free accommodation at university dormitory", insurance: "Health insurance coverage", other: "No entrance or examination fees" }),
    requirements: JSON.stringify({ nationality: "Must be a national of a country that has diplomatic relations with Japan", age: "Under 35 years old", education: "Must have completed 16 years of school education outside Japan", language: "Japanese or English proficiency (JLPT or TOEFL/IELTS)", documents: ["Application form", "Field of study and research plan", "Transcripts and graduation certificate", "Recommendation letters (2)", "Abstract of thesis or research", "Photo and passport copy", "Medical certificate", "Letter of recommendation from the university"] }),
    sourceUrl: "https://www.mext.go.jp/en/",
    source: "SCRAPED",
  },
  {
    nameEn: "Stipendium Hungaricum Scholarship",
    nameAr: "منحة Stipendium Hungaricum",
    country: "Hungary",
    university: "Participating Hungarian Universities (30+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-01-15T23:59:00Z"),
    flagUrl: "/images/flags/hungary.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Palestine", "Morocco", "Tunisia", "Lebanon"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 45,
    minimumGPA: 2.5,
    englishRequirement: "Basic English",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A Hungarian government scholarship offering full tuition waiver, monthly stipend, and dormitory accommodation for students from eligible countries across all degree levels.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver for the entire study period", allowance: "Monthly stipend of HUF 43,700 (Bachelor/Master) or HUF 140,000 (PhD)", housing: "Free dormitory place or monthly housing contribution of HUF 40,000", insurance: "Comprehensive health insurance (up to HUF 65,000/year)", travel: "Contribution of up to 200 EUR to travel costs", other: "Free visa application process" }),
    requirements: JSON.stringify({ nationality: "Citizens of eligible countries (including Egypt, Palestine, Iraq, Syria, etc.)", age: "No strict age limit, but priority given to applicants under 30", education: "High school diploma for Bachelor, Bachelor degree for Master", language: "English proficiency (TOEFL 72+/IELTS 5.5+ or equivalent)", documents: ["Online application form (DreamApply platform)", "Motivation letter", "CV", "Secondary school certificate / Bachelor's degree", "Transcript of records", "Medical certificate", "Copy of passport", "Proof of language proficiency"] }),
    sourceUrl: "https://stipendiumhungaricum.hu/",
    source: "SCRAPED",
  },
  {
    nameEn: "Chevening Scholarship (UK Government)",
    nameAr: "منحة Chevening البريطانية",
    country: "United Kingdom",
    university: "Any UK university (all Chevening-partner universities)",
    degree: "Master",
    deadline: new Date("2025-11-05T23:59:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Palestine", "Lebanon"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.2,
    englishRequirement: "IELTS 6.5",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The UK government's prestigious global scholarship program offering full tuition, living stipend, and exclusive networking opportunities for future leaders.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage (up to £18,000)", allowance: "Monthly living stipend", travel: "Economy class return airfare to the UK", housing: "Arrival allowance and departure allowance", insurance: "Health insurance (NHS surcharge covered)", other: "Exclusive networking events, leadership program, visa fees covered" }),
    requirements: JSON.stringify({ nationality: "Must be a citizen of a Chevening-eligible country (Egypt is eligible)", age: "No upper age limit", education: "Must have an undergraduate degree (equivalent to UK 2:1 honours)", experience: "At least 2 years of work experience (paid, unpaid, or voluntary)", language: "English proficiency (IELTS 6.5+ or equivalent)", documents: ["Online application form", "CV/Resume", "Three recommendation letters", "Academic transcripts and certificates", "Valid passport", "English language test results", "Statement of purpose / Personal statement"] }),
    sourceUrl: "https://www.chevening.org/",
    source: "SCRAPED",
  },
  {
    nameEn: "DAAD Scholarship (Germany) — Master & PhD",
    nameAr: "منحة DAAD الألمانية",
    country: "Germany",
    university: "Various German Universities",
    degree: "Master / PhD",
    deadline: new Date("2026-08-01T23:59:00Z"),
    flagUrl: "/images/flags/germany.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine", "Syria", "Algeria"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 38,
    minimumGPA: 2.5,
    englishRequirement: "TOEFL 80 or IELTS 6.0 (depends on program)",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT", "RESEARCH_PROPOSAL"],
    description: "DAAD offers a wide range of scholarships for graduates, doctoral candidates, and postdocs to study and research at German universities. One of the most popular scholarships for Egyptian students.",
    benefits: JSON.stringify({ tuition: "No tuition fees at German public universities", allowance: "Monthly stipend of €934 (Master) or €1,300 (PhD)", travel: "Travel allowance if not Germany-resident", insurance: "Health, accident and liability insurance", housing: "Housing subsidy possible", other: "Language course funding (2-6 months), annual research allowance" }),
    requirements: JSON.stringify({ nationality: "Open to all developing countries including Egypt", age: "No strict limit but typically under 36", education: "Bachelor's degree for Master, Master's degree for PhD", language: "Depends on program — English (TOEFL/IELTS) or German (DSH/TestDaF)", documents: ["Online application", "CV (Europass format)", "Letter of motivation", "Letter of recommendation", "Academic transcripts", "Research proposal (for PhD)", "Language certificate", "Letter from host professor (for PhD)"] }),
    sourceUrl: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    source: "SCRAPED",
  },
  {
    nameEn: "Turkiye Burslari Scholarship (Türkiye)",
    nameAr: "منحة تركيا بورسلاري",
    country: "Turkey",
    university: "Participating Turkish Universities (60+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-02-20T23:59:00Z"),
    flagUrl: "/images/flags/turkey.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Syria", "Iraq", "Morocco", "Tunisia", "Algeria"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 2.5,
    englishRequirement: "Depends on program (some in English, some in Turkish)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A fully-funded Turkish government scholarship program covering tuition, monthly stipend, accommodation, and health insurance. Very popular among Arab students due to cultural proximity.",
    benefits: JSON.stringify({ tuition: "Full university tuition fee waiver", allowance: "Monthly stipend: TRY 1,250 (Bachelor), TRY 1,600 (Master), TRY 2,400 (PhD)", housing: "Free accommodation in state university dormitories", travel: "One-time flight ticket (arrival and departure)", insurance: "Comprehensive health insurance", other: "One-year Turkish language course at TÖMER, free academic support services" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities except Turkish citizens", age: "Under 30 for Bachelor, under 35 for Master, under 40 for PhD", education: "High school diploma for Bachelor, Bachelor degree for Master", language: "No initial language requirement; one-year Turkish prep provided", documents: ["Online application form", "Educational documents (diploma, transcript)", "International exam scores (if any)", "International language test scores (if any)", "Research proposal (for PhD)", "Valid passport"] }),
    sourceUrl: "https://www.turkiyeburslari.gov.tr/",
    source: "SCRAPED",
  },
  {
    nameEn: "Erasmus Mundus Joint Master Degree",
    nameAr: "منحة إيراسموس موندوس",
    country: "Multiple (Europe)",
    university: "Consortium of European universities",
    degree: "Master",
    deadline: new Date("2026-01-10T23:59:00Z"),
    flagUrl: "/images/flags/eu.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Syria", "Morocco", "Tunisia", "Algeria"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Economics", "Law", "Political Science", "Biology", "Medicine", "Physics", "Mathematics"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5-7.0 (program-dependent)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "Study at 2+ European universities in different countries, earning a joint or double degree. Fully funded including tuition, travel, and living costs. Extremely prestigious and globally competitive.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage (up to €9,000/year)", allowance: "Monthly living allowance of €1,400 for 24 months", travel: "Travel costs including visa and installation costs (€3,000-€4,000)", insurance: "Health insurance covered", housing: "Housing support included in living allowance", other: "Participation in multiple European academic environments" }),
    requirements: JSON.stringify({ nationality: "Open to all non-European students from around the world", age: "No age limit", education: "Bachelor's degree (equivalent to 180 ECTS)", language: "English proficiency (TOEFL 92+/IELTS 6.5-7.0)", documents: ["Online application per program", "Bachelor's degree certificate and transcripts", "Motivation letter", "CV/Resume", "Two recommendation letters", "Passport copy", "English language certificate", "Proof of residence"] }),
    sourceUrl: "https://erasmus-plus.ec.europa.eu/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
    source: "SCRAPED",
  },
  {
    nameEn: "Fulbright Foreign Student Program (USA)",
    nameAr: "منحة فولبرايت الأمريكية",
    country: "United States",
    university: "Various US Universities",
    degree: "Master / PhD",
    deadline: new Date("2026-04-15T23:59:00Z"),
    flagUrl: "/images/flags/usa.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Algeria"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80+ or IELTS 6.5+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The flagship international educational exchange program sponsored by the U.S. government, offering full funding for graduate study in the United States.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage at the host university", allowance: "Monthly living stipend", travel: "Round-trip airfare to the US", housing: "Accommodation support", insurance: "Comprehensive health and accident insurance", other: "Pre-departure orientation, enrichment programs, visa support" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible countries (Egypt included)", age: "Under 40 years old", education: "Bachelor's degree (equivalent to US 4-year degree)", language: "English proficiency (TOEFL 80+ or IELTS 6.5+)", documents: ["Online application (Embassy Parcel)", "CV/Resume", "Personal statement / Study objective", "Three recommendation letters", "Academic transcripts", "Standardized test scores (GRE/GMAT if required)", "Passport copy"] }),
    sourceUrl: "https://foreign.fulbrightonline.org/",
    source: "SCRAPED",
  },
  {
    nameEn: "Gates Cambridge Scholarship (UK)",
    nameAr: "منحة جيتس كامبريدج",
    country: "United Kingdom",
    university: "University of Cambridge",
    degree: "Master / PhD",
    deadline: new Date("2025-10-15T23:59:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: 3.5,
    englishRequirement: "IELTS 7.0-7.5",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["RESEARCH_PROPOSAL", "PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A highly prestigious full-cost scholarship to study at the University of Cambridge, founded by the Bill and Melinda Gates Foundation. Covers the full cost of study for outstanding applicants.",
    benefits: JSON.stringify({ tuition: "Full Cambridge tuition fee (University Composition Fee)", allowance: "Annual maintenance allowance of £21,000", travel: "Round-trip airfare at start and end of program", housing: "College accommodation support", insurance: "Comprehensive health insurance (NHS)", other: "Academic development funding (up to £2,000), family allowance if applicable, visa costs covered" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities outside the UK", age: "No age limit", education: "First-class or strong upper-second-class Bachelor's degree", language: "English proficiency (TOEFL 100+/IELTS 7.0-7.5)", documents: ["Online application via Cambridge system", "Research proposal (for PhD)", "Personal statement", "CV/Resume", "Three academic references", "Academic transcripts", "GRE scores (if required by program)", "Portfolio (if applicable)"] }),
    sourceUrl: "https://www.gatescambridge.org/",
    source: "MANUAL",
  },
  {
    nameEn: "Rhodes Scholarship (Oxford)",
    nameAr: "منحة رودس — أوكسفورد",
    country: "United Kingdom",
    university: "University of Oxford",
    degree: "Master / PhD",
    deadline: new Date("2025-09-15T23:59:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 28,
    minimumGPA: 3.5,
    englishRequirement: "IELTS 7.0+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The oldest and one of the most prestigious international scholarship programs, enabling outstanding students to study at the University of Oxford.",
    benefits: JSON.stringify({ tuition: "Full Oxford tuition fees", allowance: "Annual living stipend of approximately £19,092", travel: "Round-trip airfare to the UK", housing: "College accommodation included", insurance: "Health insurance (NHS surcharge)", other: "Application fee coverage, visa support, access to Rhodes House and networking" }),
    requirements: JSON.stringify({ nationality: "Citizens of eligible countries (Egypt included since 2021)", age: "Under 28 years old (born after October 1 of the application year - 2)", education: "First-class or strong upper-second-class Honours degree", language: "English proficiency (TOEFL 100+/IELTS 7.0+)", documents: ["Online Rhodes application", "Personal statement (1,000 words)", "CV", "5-8 references", "Academic transcripts and degree certificates", "Standardized test scores (if needed)", "Photo and identity documents"] }),
    sourceUrl: "https://www.rhodeshouse.ox.ac.uk/",
    source: "MANUAL",
  },
  {
    nameEn: "Italian Government Scholarship (MAECI)",
    nameAr: "منحة الحكومة الإيطالية",
    country: "Italy",
    university: "Various Italian Universities",
    degree: "Master / PhD / Research",
    deadline: new Date("2026-06-14T23:59:00Z"),
    flagUrl: "/images/flags/italy.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Algeria", "Palestine"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 36,
    minimumGPA: 2.5,
    englishRequirement: "Depends on program (Italian B2 or English B2)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Italian government offers scholarships to international students to study at Italian higher education institutions. Covers tuition, stipend, and health insurance.",
    benefits: JSON.stringify({ tuition: "No tuition fees at public universities (scholarship holders)", allowance: "Monthly stipend of €900 (€1,100 for PhD)", travel: "Travel allowance covered in some cases", insurance: "Health and accident insurance for the duration of study", housing: "Housing support through DSU benefits", other: "Free Italian language courses at Università per Stranieri" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible countries", age: "Under 36 years old", education: "Bachelor's degree for Master, Master's for PhD", language: "Italian or English proficiency (B2 level minimum)", documents: ["Online application (Study in Italy portal)", "Proof of language proficiency", "Academic transcripts and degree certificates", "Letter of motivation", "Recommendation letters (2)", "Research proposal (for PhD)", "Passport copy"] }),
    sourceUrl: "https://www.esteri.it/en/opportunita/borse-di-studio/",
    source: "SCRAPED",
  },
  {
    nameEn: "Eiffel Excellence Scholarship (France)",
    nameAr: "منحة إيفل الفرنسية",
    country: "France",
    university: "Participating French Universities",
    degree: "Master / PhD",
    deadline: new Date("2025-12-10T23:59:00Z"),
    flagUrl: "/images/flags/france.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Algeria"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Economics", "Law", "Political Science", "Environmental Science"],
    minimumAge: 18,
    maximumAge: 32,
    minimumGPA: 3.3,
    englishRequirement: "TOEFL 80+ or IELTS 6.5+ (varies by program)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A prestigious French government scholarship program that supports top international students pursuing Master's or PhD programs at French institutions.",
    benefits: JSON.stringify({ tuition: "No tuition fees (scholarship is monthly allowance)", allowance: "Monthly stipend of €1,031 (Master) or €1,700 (PhD)", travel: "International travel costs not included", housing: "Assistance with finding accommodation", insurance: "Health insurance covered", other: "Cultural activities and networking events, support from Campus France" }),
    requirements: JSON.stringify({ nationality: "Open to non-French nationals (dual French not eligible)", age: "Under 30 for Master, under 35 for PhD", education: "Excellent academic record, Bachelor for Master, Master for PhD", language: "French or English proficiency depending on program", documents: ["Application submitted by the French host institution", "Academic transcripts and diplomas", "CV and motivation letter", "Recommendation letters (2-3)", "Language proficiency certificate", "Research proposal (for PhD)"] }),
    sourceUrl: "https://www.campusfrance.org/en/the-eiffel-scholarship-program",
    source: "SCRAPED",
  },
  {
    nameEn: "Holland Scholarship (Netherlands)",
    nameAr: "منحة هولندا الدراسية",
    country: "Netherlands",
    university: "Participating Dutch Research Universities and Universities of Applied Sciences",
    degree: "Bachelor / Master",
    deadline: new Date("2026-02-01T23:59:00Z"),
    flagUrl: "/images/flags/netherlands.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["BACHELOR", "MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ or TOEFL 90+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A Dutch government scholarship for international students from outside the EEA applying for full-time Bachelor's or Master's programs at participating Dutch institutions.",
    benefits: JSON.stringify({ tuition: "Partial tuition fee waiver (€5,000 in the first year)", allowance: "€5,000 one-time grant in the first academic year", travel: "Not covered by the scholarship", housing: "Housing assistance through the university", insurance: "Student health insurance required (not covered)", other: "Some institutions supplement with additional funding" }),
    requirements: JSON.stringify({ nationality: "Non-EEA nationals from eligible countries (Egypt included)", age: "No strict age limit", education: "High school for Bachelor, Bachelor for Master", language: "English proficiency (TOEFL 90+/IELTS 6.5+)", documents: ["Apply to the participating Dutch university directly", "Admission letter from the university", "Proof of English proficiency", "Motivation letter specific to the scholarship", "CV/Resume", "Passport copy"] }),
    sourceUrl: "https://www.studyinholland.nl/scholarsities/holland-scholarship",
    source: "SCRAPED",
  },
  {
    nameEn: "Swedish Institute Scholarship for Global Professionals",
    nameAr: "منحة المعهد السويدي",
    country: "Sweden",
    university: "Participating Swedish Universities",
    degree: "Master",
    deadline: new Date("2026-02-12T23:59:00Z"),
    flagUrl: "/images/flags/sweden.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 45,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ or TOEFL 90+",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A Swedish government scholarship for highly qualified international students pursuing Master's programs in Sweden. Focuses on future global leaders.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver at the host Swedish university", allowance: "Monthly living allowance of SEK 12,000", travel: "International travel grant of SEK 15,000", insurance: "Comprehensive health insurance", housing: "Housing assistance through the university", other: "Membership in the Swedish Institute Network for Future Global Professionals (NFGP), leadership training" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible countries (Egypt included)", age: "No strict age limit, but work experience preferred", education: "Bachelor's degree of at least 180 ECTS", experience: "At least 3,000 hours of work experience or volunteer experience", language: "English proficiency (TOEFL 90+/IELTS 6.5+)", documents: ["Online application through University Admissions", "Motivation letter", "CV and letters of recommendation", "Proof of work experience", "Academic transcripts and degree certificate", "Valid passport"] }),
    sourceUrl: "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
    source: "SCRAPED",
  },
  {
    nameEn: "Swiss Government Excellence Scholarship",
    nameAr: "منحة الحكومة السويسرية",
    country: "Switzerland",
    university: "Participating Swiss Universities and ETH Zurich / EPFL",
    degree: "PhD / Postdoc / Research",
    deadline: new Date("2025-12-10T23:59:00Z"),
    flagUrl: "/images/flags/switzerland.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Biology", "Physics", "Mathematics", "Environmental Science", "Medicine", "Chemistry"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.3,
    englishRequirement: "TOEFL 90+ or IELTS 6.5+",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["RESEARCH_PROPOSAL", "MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Swiss Government Excellence Scholarship promotes international exchange and research cooperation. A prestigious opportunity to conduct doctoral or postdoctoral research in Switzerland.",
    benefits: JSON.stringify({ tuition: "No tuition fees at Swiss public universities", allowance: "Monthly stipend of CHF 1,920 (PhD) or CHF 3,500 (Postdoc)", travel: "Annual return airfare to Switzerland", insurance: "Compulsory health insurance partially covered", housing: "Housing allowance of CHF 300-500 per month", other: "Research contribution of CHF 1,500/year (PhD) or CHF 3,000/year (Postdoc)" }),
    requirements: JSON.stringify({ nationality: "Open to graduates from eligible countries (Egypt included)", age: "Under 35 for PhD applications", education: "Master's degree for PhD, PhD for Postdoc", language: "English proficiency (TOEFL 90+/IELTS 6.5+)", documents: ["Application form", "Research proposal (detailed, up to 10 pages)", "CV", "Two recommendation letters", "Academic transcripts", "Letter from host professor in Switzerland", "Health certificate", "Language proficiency proof"] }),
    sourceUrl: "https://www.sbfi.admin.ch/sbfi/en/home/education/international-cooperation/internationale-mobilitaet/staatssekretariats-fuer-bildung-und-forschung-sbfi.html",
    source: "SCRAPED",
  },
  {
    nameEn: "KAUST Fellowship (Saudi Arabia)",
    nameAr: "منحة كاوست — جامعة الملك عبدالله",
    country: "Saudi Arabia",
    university: "King Abdullah University of Science and Technology (KAUST)",
    degree: "Master / PhD",
    deadline: null,
    flagUrl: "/images/flags/saudi-arabia.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Morocco", "Tunisia", "Algeria", "Syria", "Iraq"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Biology", "Physics", "Mathematics", "Chemistry", "Environmental Science"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 79+ or IELTS 6.5+",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "KAUST's prestigious graduate fellowship for Master's and PhD students in science, engineering, and technology at one of the world's most advanced research universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Monthly stipend of $20,000-30,000 annually (tax-free)", travel: "Round-trip airfare at start and end of program", housing: "Free on-campus housing (furnished apartments)", insurance: "Comprehensive medical and dental insurance", other: "Relocation support, free laptop, research and travel grants, access to state-of-the-art labs" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities (male and female)", age: "No age limit", education: "Bachelor's degree for Master, Master's for PhD", language: "English proficiency (TOEFL 79+/IELTS 6.5+)", documents: ["Online application", "Statement of purpose", "CV/Resume", "Three recommendation letters", "Official transcripts", "Valid passport", "GRE scores (recommended but not required)"] }),
    sourceUrl: "https://www.kaust.edu.sa/study/graduate-program",
    source: "SCRAPED",
  },
  {
    nameEn: "King Saud University Scholarship (Saudi Arabia)",
    nameAr: "منحة جامعة الملك سعود",
    country: "Saudi Arabia",
    university: "King Saud University",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-05-30T23:59:00Z"),
    flagUrl: "/images/flags/saudi-arabia.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Sudan", "Syria", "Yemen"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 2.5,
    englishRequirement: "Depends on program",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT"],
    description: "KSU offers comprehensive scholarships for international students at one of Saudi Arabia's largest and most prestigious universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver", allowance: "Monthly stipend of SAR 900-1,300", travel: "Round-trip airfare annually", housing: "Free on-campus accommodation", insurance: "Medical care at university hospitals", other: "Free textbooks, research support, access to university facilities" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities (competitive for non-Saudi)", age: "Under 25 for Bachelor, under 30 for Master, under 35 for PhD", education: "High school for Bachelor, Bachelor for Master, Master for PhD", language: "Must pass the university's language requirements", documents: ["Online application", "Academic certificates and transcripts", "Passport copy", "Recommendation letters", "Medical exam report", "Language proficiency proof"] }),
    sourceUrl: "https://ksu.edu.sa/en/admission/scholarship",
    source: "MANUAL",
  },
  {
    nameEn: "Mohammed Bin Rashid Al Maktoum Scholarship (UAE)",
    nameAr: "منحة محمد بن راشد آل مكتوم",
    country: "United Arab Emirates",
    university: "Various UAE Universities",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-07-15T23:59:00Z"),
    flagUrl: "/images/flags/uae.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Syria", "Morocco"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.0+ or TOEFL 80+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A prestigious UAE government scholarship for outstanding international students to study at top UAE universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Monthly stipend for living expenses", travel: "Annual round-trip airfare", housing: "Free or subsidized accommodation", insurance: "Comprehensive health insurance", other: "Book allowance, laptop provided, mentorship program" }),
    requirements: JSON.stringify({ nationality: "Open to nationals of eligible Arab and Muslim countries", age: "Under 30 for Bachelor, under 35 for Master, under 40 for PhD", education: "High school for Bachelor, Bachelor for Master", language: "Arabic or English proficiency", documents: ["Online application", "Academic transcripts and certificates", "Passport and identity documents", "Recommendation letters", "Personal statement", "Language proficiency proof", "Medical fitness certificate"] }),
    sourceUrl: "https://www.mbrscholarship.ae/",
    source: "MANUAL",
  },
  {
    nameEn: "Qatar University International Student Scholarship",
    nameAr: "منحة جامعة قطر",
    country: "Qatar",
    university: "Qatar University",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-03-31T23:59:00Z"),
    flagUrl: "/images/flags/qatar.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Syria", "Morocco", "Tunisia", "Algeria"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.0+ or TOEFL 80+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "Qatar University offers competitive scholarships for high-achieving international students across all levels of study.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver (100%) or partial (50%)", allowance: "Monthly stipend of QAR 2,000-3,000", travel: "Annual round-trip airfare", housing: "Free on-campus housing", insurance: "Health insurance coverage", other: "Free textbooks and study materials" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities", age: "Under 30 for Bachelor, under 40 for graduate programs", education: "High school for Bachelor, relevant degree for graduate", language: "English or Arabic proficiency depending on program", documents: ["Online application", "High school or university transcripts", "Standardized test scores (SAT/ACT if any)", "Passport copy", "Recommendation letters", "Personal statement"] }),
    sourceUrl: "https://www.qu.edu.qa/admissions/scholarships",
    source: "MANUAL",
  },
  {
    nameEn: "Chinese Government Scholarship (CSC)",
    nameAr: "منحة الحكومة الصينية",
    country: "China",
    university: "Participating Chinese Universities (280+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-03-01T23:59:00Z"),
    flagUrl: "/images/flags/china.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine", "Syria", "Yemen", "Sudan"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 2.5,
    englishRequirement: "Depends on program (Chinese HSK4+ or English proficiency)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT"],
    description: "A comprehensive Chinese government scholarship covering tuition, accommodation, and living expenses for international students at Chinese universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver", allowance: "Monthly stipend: CNY 2,500 (Bachelor), CNY 3,000 (Master), CNY 3,500 (PhD)", travel: "International travel costs partially covered", housing: "Free on-campus dormitory accommodation", insurance: "Comprehensive medical insurance (¥800/year)", other: "One-year Chinese language study option, cultural activities" }),
    requirements: JSON.stringify({ nationality: "Open to all non-Chinese nationals (Egypt included)", age: "Under 25 for Bachelor, under 35 for Master, under 40 for PhD", education: "High school for Bachelor, Bachelor for Master, Master for PhD", language: "HSK 4+ for Chinese-taught programs or IELTS 6.0 for English-taught", documents: ["Online application via CSC portal", "Highest diploma and transcripts", "Study or research plan", "Two recommendation letters", "Passport copy", "Language proficiency certificate", "Physical examination form", "Pre-admission letter from Chinese university (optional)"] }),
    sourceUrl: "https://www.campuschina.org/",
    source: "SCRAPED",
  },
  {
    nameEn: "GKS Scholarship (Global Korea Scholarship — KGSP)",
    nameAr: "منحة كوريا الجنوبية GKS",
    country: "South Korea",
    university: "Participating Korean Universities (65+ universities)",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-03-15T23:59:00Z"),
    flagUrl: "/images/flags/south-korea.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80+ or IELTS 6.0+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Korean government's flagship scholarship program that supports international students to pursue degrees in Korea with full funding.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Monthly stipend of KRW 900,000 (Bachelor) or KRW 1,200,000 (Graduate)", travel: "Round-trip airfare to Korea", housing: "Free on-campus housing or housing allowance", insurance: "Korean health insurance (National Health Insurance)", other: "Korean language training (1 year), research support (graduate), settlement allowance (KRW 200,000), completion grant (KRW 100,000)" }),
    requirements: JSON.stringify({ nationality: "Citizens of eligible countries (Egypt qualifies through embassy track)", age: "Under 25 for Bachelor, under 40 for Graduate", education: "High school for Bachelor, Bachelor for Master, Master for PhD", language: "English proficiency (TOEFL 80+/IELTS 6.0+)", documents: ["Online application (Study in Korea portal)", "Personal statement and study plan", "Academic transcripts and diplomas", "Two recommendation letters", "Passport and identity documents", "Language proficiency test scores", "Medical certificate", "Portfolio (if applicable)"] }),
    sourceUrl: "https://www.studyinkorea.go.kr/",
    source: "SCRAPED",
  },
  {
    nameEn: "Australia Awards Scholarship",
    nameAr: "منحة جوائز أستراليا",
    country: "Australia",
    university: "Participating Australian Universities",
    degree: "Master / PhD",
    deadline: new Date("2026-04-30T23:59:00Z"),
    flagUrl: "/images/flags/australia.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Morocco"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Economics", "Law", "Political Science", "Medicine"],
    minimumAge: 18,
    maximumAge: 45,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ (no band less than 6.0)",
    requiresResearch: false,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Australian Government's flagship scholarship program for development-focused professionals from developing countries to study at Australian universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Fortnightly living allowance (approximately AUD 1,000)", travel: "Round-trip airfare to Australia", housing: "Establishment allowance, accommodation support", insurance: "Comprehensive health insurance (OSHC)", other: "Pre-departure and in-country support, academic support, fieldwork allowance for research" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible developing countries (Egypt included)", age: "No strict age limit", education: "Bachelor's degree (equivalent to Australian degree)", experience: "At least 2 years of work experience preferred", language: "English proficiency (IELTS 6.5+ with no band below 6.0)", documents: ["Online application", "Academic transcripts and degree certificates", "CV/Resume", "Recommendation letters (2)", "Personal statement", "Proof of employment", "English language test results", "Passport copy"] }),
    sourceUrl: "https://www.dfat.gov.au/people-people/australia-awards-scholarships",
    source: "SCRAPED",
  },
  {
    nameEn: "Vanier Canada Graduate Scholarship",
    nameAr: "منحة فانييه الكندية",
    country: "Canada",
    university: "Participating Canadian Universities",
    degree: "PhD",
    deadline: new Date("2025-11-07T23:59:00Z"),
    flagUrl: "/images/flags/canada.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: 3.5,
    englishRequirement: "TOEFL 90+ or IELTS 7.0+",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["RESEARCH_PROPOSAL", "PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Vanier CGS is a prestigious Canadian government scholarship that supports world-class doctoral students demonstrating leadership skills and high academic achievement.",
    benefits: JSON.stringify({ tuition: "No direct tuition coverage (separate funding)", allowance: "Annual stipend of CAD 50,000 for 3 years", travel: "Up to CAD 5,000 for research travel", housing: "Not covered", insurance: "University health insurance (varies)", other: "Research allowance, leadership development opportunities" }),
    requirements: JSON.stringify({ nationality: "Open to Canadian and international students (Egypt included)", age: "No age limit", education: "Master's degree or equivalent", language: "English or French proficiency", documents: ["Online application", "Research proposal", "Leadership profile", "Three recommendation letters (including one from your proposed supervisor)", "Academic transcripts", "CV/Resume", "Proof of citizenship"] }),
    sourceUrl: "https://vanier.gc.ca/",
    source: "MANUAL",
  },
  {
    nameEn: "Lester B. Pearson International Scholarship (University of Toronto)",
    nameAr: "منحة ليستر ب. بيرسون — تورنتو",
    country: "Canada",
    university: "University of Toronto",
    degree: "Bachelor",
    deadline: new Date("2025-11-15T23:59:00Z"),
    flagUrl: "/images/flags/canada.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Morocco", "Tunisia"],
    eligibleEducation: ["BACHELOR"],
    fieldOfStudy: ["Any"],
    minimumAge: 16,
    maximumAge: 25,
    minimumGPA: 3.5,
    englishRequirement: "TOEFL 100+ or IELTS 7.0+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The most prestigious scholarship at the University of Toronto, recognizing exceptional international students who demonstrate academic excellence and leadership potential.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage for 4 years", allowance: "Living allowance of approximately CAD 5,000/year", travel: "Round-trip airfare", housing: "Free on-campus residence for 4 years", insurance: "Health insurance (UHIP)", other: "Access to Pearson mentorship program, leadership seminars, and exclusive networking events" }),
    requirements: JSON.stringify({ nationality: "International students (non-Canadian) from any country", age: "No strict age limit", education: "Outstanding high school academic record", language: "English proficiency (TOEFL 100+/IELTS 7.0+)", documents: ["Apply to University of Toronto first (for admission)", "Online Pearson Scholarship application", "Personal essay", "List of extracurricular activities", "Recommendation letter from school", "Academic transcripts", "Proof of English proficiency"] }),
    sourceUrl: "https://future.utoronto.ca/pearson-admissions/",
    source: "MANUAL",
  },
  {
    nameEn: "Heinrich Böll Foundation Scholarship (Germany)",
    nameAr: "منحة مؤسسة هاينريش بول",
    country: "Germany",
    university: "Various German Universities",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-03-01T23:59:00Z"),
    flagUrl: "/images/flags/germany.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Morocco", "Tunisia", "Syria"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Political Science", "Economics", "Law"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.0,
    englishRequirement: "German B2+ or English B2+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A German political foundation scholarship for international students committed to environmental sustainability, democracy, and social justice.",
    benefits: JSON.stringify({ tuition: "No tuition fees at German public universities", allowance: "Monthly stipend of €934 (Bachelor/Master) or €1,300 (PhD)", travel: "Travel allowance for non-European students", insurance: "Health insurance contributions covered", housing: "Housing subsidy of €70/month possible", other: "Book allowance, seminar participation, language course support, mentoring program" }),
    requirements: JSON.stringify({ nationality: "Open to international students, especially from developing countries", age: "No strict age limit", education: "Admission to a German university for Bachelor, Master, or PhD", language: "Good German or English skills (B2+ level)", documents: ["Online application", "Motivation letter (explaining social/political commitment)", "CV", "Two recommendation letters", "Academic transcripts", "University admission or enrollment proof", "Proof of language proficiency", "Essay on current political/social topic"] }),
    sourceUrl: "https://www.boell.de/en/foundation/scholarships",
    source: "MANUAL",
  },
  {
    nameEn: "Orange Tulip Scholarship (Netherlands)",
    nameAr: "منحة أورانج توليب الهولندية",
    country: "Netherlands",
    university: "Participating Dutch Universities (specific to each)",
    degree: "Bachelor / Master",
    deadline: new Date("2026-04-01T23:59:00Z"),
    flagUrl: "/images/flags/netherlands.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["BACHELOR", "MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ or TOEFL 90+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A Dutch government scholarship specifically for students from select countries, offered by various Dutch universities and the Nuffic Neso network.",
    benefits: JSON.stringify({ tuition: "Partial to full tuition fee waiver (varies by university)", allowance: "€5,000-€15,000 depending on institution", travel: "Not covered by the scholarship", housing: "Housing assistance may be available", insurance: "Student health insurance required", other: "Visa application support, orientation program, Dutch language course" }),
    requirements: JSON.stringify({ nationality: "Citizens of eligible countries (Egypt included)", age: "No strict age limit", education: "High school for Bachelor, Bachelor for Master", language: "English proficiency (TOEFL 90+/IELTS 6.5+)", documents: ["Admission letter from participating Dutch university", "Motivation letter", "Academic transcripts and diplomas", "CV/Resume", "Recommendation letters", "Proof of English proficiency", "Passport copy"] }),
    sourceUrl: "https://www.neso-india.org/orangetulipscholarship",
    source: "MANUAL",
  },
  {
    nameEn: "University of Tokyo — ADB Scholarship",
    nameAr: "منحة بنك التنمية الآسيوي — طوكيو",
    country: "Japan",
    university: "University of Tokyo",
    degree: "Master / PhD",
    deadline: new Date("2026-02-15T23:59:00Z"),
    flagUrl: "/images/flags/japan.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Economics", "Political Science"],
    minimumAge: 18,
    maximumAge: 45,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80+ or IELTS 6.0+",
    requiresResearch: true,
    requiresWorkExp: true,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["RESEARCH_PROPOSAL", "MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The ADB-Japan Scholarship at the University of Tokyo provides full funding for graduate studies in economics, management, science, and engineering.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Monthly stipend of ¥150,000", travel: "Round-trip airfare to Japan", housing: "Housing allowance of ¥110,000/month", insurance: "Health insurance coverage", other: "Book and equipment allowance (¥17,000/month), research support, language training" }),
    requirements: JSON.stringify({ nationality: "Citizens of ADB borrowing member countries (Egypt included)", age: "Under 45 years old", education: "Bachelor's degree for Master, Master's for PhD", experience: "At least 2 years of professional work experience", language: "English proficiency (TOEFL 80+/IELTS 6.0+)", documents: ["Online application", "Research proposal", "Academic transcripts", "CV/Resume", "Recommendation letters (2)", "Proof of work experience", "English language test scores"] }),
    sourceUrl: "https://www.adb.org/what-we-do/scholarships/adb-japan-scholarship-program",
    source: "MANUAL",
  },
  {
    nameEn: "ETH Zurich Excellence Scholarship (Switzerland)",
    nameAr: "منحة ETH زيورخ",
    country: "Switzerland",
    university: "ETH Zurich",
    degree: "Master",
    deadline: new Date("2025-12-15T23:59:00Z"),
    flagUrl: "/images/flags/switzerland.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Engineering", "Computer Science", "Biology", "Physics", "Mathematics", "Chemistry", "Environmental Science"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.5,
    englishRequirement: "TOEFL 100+ or IELTS 7.0+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Excellence Scholarship & Opportunity Programme (ESOP) at ETH Zurich offers full funding for outstanding Master's students.",
    benefits: JSON.stringify({ tuition: "Partial tuition fee coverage (CHF 730/semester remains)", allowance: "CHF 11,000 per semester for living expenses", travel: "Not covered", housing: "Housing assistance through ETH Wohnen", insurance: "Swiss health insurance required", other: "Mentoring program, access to ETH network, leadership development opportunities" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities", age: "No strict age limit", education: "Excellent Bachelor's degree from a recognized university", language: "English proficiency (TOEFL 100+/IELTS 7.0+)", documents: ["Online application via eApply portal", "CV with academic achievements", "Statement of purpose", "Two recommendation letters", "Academic transcripts (all semesters)", "Letter of motivation for the program", "GRE scores (recommended)"] }),
    sourceUrl: "https://ethz.ch/en/studies/master/application/excellence-scholarship.html",
    source: "MANUAL",
  },
  {
    nameEn: "University of Warsaw — Polish Government Scholarship",
    nameAr: "منحة الحكومة البولندية",
    country: "Poland",
    university: "Various Polish Universities",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-06-30T23:59:00Z"),
    flagUrl: "/images/flags/poland.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Palestine", "Morocco", "Tunisia", "Syria"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 2.5,
    englishRequirement: "Basic English",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT"],
    description: "The Polish Government offers scholarships through the NAWA (National Agency for Academic Exchange) for international students at Polish universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver", allowance: "Monthly stipend of PLN 1,500 (Bachelor/Master) or PLN 2,500 (PhD)", travel: "Round-trip airfare covered", housing: "Free dormitory accommodation", insurance: "Health insurance coverage", other: "Polish language course, integration activities" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible countries (Egypt included)", age: "Under 30 for Bachelor, under 40 for graduate", education: "High school for Bachelor, Bachelor for Master, Master for PhD", language: "English or Polish language proficiency", documents: ["Online application via NAWA portal", "Academic transcripts and diplomas", "Motivation letter", "CV", "Language proficiency certificate", "Passport copy", "Medical certificate"] }),
    sourceUrl: "https://nawa.gov.pl/en/",
    source: "MANUAL",
  },
  {
    nameEn: "Sawiris Foundation Scholarship for Egyptians",
    nameAr: "منحة مؤسسة ساويرس",
    country: "Egypt",
    university: "Various Egyptian Universities / International",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-06-01T23:59:00Z"),
    flagUrl: "/images/flags/egypt.svg",
    eligibleCountries: ["Egypt"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80+ or IELTS 6.0+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Sawiris Foundation offers scholarships for outstanding Egyptian students to pursue undergraduate and graduate studies at top universities in Egypt and abroad.",
    benefits: JSON.stringify({ tuition: "Full or partial tuition coverage", allowance: "Monthly living stipend", travel: "Travel costs covered for international programs", housing: "Housing allowance provided", insurance: "Health insurance coverage", other: "Mentorship program, career development support, networking events" }),
    requirements: JSON.stringify({ nationality: "Egyptian citizens only", age: "Under 25 for Bachelor, under 35 for Master, under 40 for PhD", education: "High school for Bachelor, Bachelor for Master", language: "English proficiency (TOEFL 80+/IELTS 6.0+)", documents: ["Online application via Sawiris platform", "Academic transcripts and certificates", "Personal statement", "CV/Resume", "Recommendation letters (2-3)", "Proof of financial need", "English language test scores", "Portfolio (if applicable)"] }),
    sourceUrl: "https://www.sawirisfoundation.org/",
    source: "MANUAL",
  },
  {
    nameEn: "DAAD GERSs (German Egyptian Research Scholarships)",
    nameAr: "منحة DAAD المصرية الألمانية للبحوث",
    country: "Germany",
    university: "Various German Universities",
    degree: "Master / PhD",
    deadline: new Date("2026-05-15T23:59:00Z"),
    flagUrl: "/images/flags/germany.svg",
    eligibleCountries: ["Egypt"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Biology", "Physics", "Mathematics", "Chemistry", "Medicine"],
    minimumAge: 18,
    maximumAge: 38,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80+ or IELTS 6.0+",
    requiresResearch: true,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["RESEARCH_PROPOSAL", "MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A DAAD program specifically for Egyptian graduate students and researchers to conduct research or pursue degrees at German universities.",
    benefits: JSON.stringify({ tuition: "No tuition fees at German public universities", allowance: "Monthly stipend of €934 (Master) or €1,300 (PhD)", travel: "International travel allowance", insurance: "Health, accident and liability insurance", housing: "Housing subsidy possible", other: "Language course, research allowance, and supervision support" }),
    requirements: JSON.stringify({ nationality: "Egyptian citizens only", age: "Under 36 typically", education: "Bachelor's degree for Master, Master's for PhD", language: "English or German proficiency", documents: ["Online application via DAAD portal", "Research proposal (for PhD)", "CV (Europass format)", "Motivation letter", "Recommendation letters (2)", "Academic transcripts and degree certificates", "Letter from German supervisor (for PhD)", "Language certificate"] }),
    sourceUrl: "https://www.daad.eg/",
    source: "SCRAPED",
  },
  {
    nameEn: "Mälardalen University Scholarship (Sweden)",
    nameAr: "منحة جامعة مالاردالين السويدية",
    country: "Sweden",
    university: "Mälardalen University",
    degree: "Master",
    deadline: new Date("2026-01-15T23:59:00Z"),
    flagUrl: "/images/flags/sweden.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Engineering", "Computer Science", "Economics"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ or TOEFL 90+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "A Swedish university scholarship offering partial to full tuition waivers for international Master's students.",
    benefits: JSON.stringify({ tuition: "Up to 100% tuition fee waiver", allowance: "Not provided", travel: "Not covered", housing: "Housing assistance through the university", insurance: "Student insurance included", other: "Access to university facilities and career support" }),
    requirements: JSON.stringify({ nationality: "Non-EU/EEA nationals from eligible countries", age: "No strict age limit", education: "Bachelor's degree in a relevant field", language: "English proficiency (TOEFL 90+/IELTS 6.5+)", documents: ["Apply for admission via universityadmissions.se", "Submit separate scholarship application", "Motivation letter", "CV", "Academic transcripts", "Proof of English proficiency", "Portfolio (if applicable)"] }),
    sourceUrl: "https://www.mdu.se/en/malardalen-university/education/scholarships",
    source: "MANUAL",
  },
  {
    nameEn: "Austrian Government Scholarship (OeAD)",
    nameAr: "منحة النمسا الدراسية",
    country: "Austria",
    university: "Various Austrian Universities",
    degree: "Master / PhD / Research",
    deadline: new Date("2026-03-01T23:59:00Z"),
    flagUrl: "/images/flags/austria.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 2.5,
    englishRequirement: "Depends on program (German B2+ or English B2+)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Austrian government through OeAD offers scholarships for international students to study at Austrian universities of applied sciences and arts.",
    benefits: JSON.stringify({ tuition: "No tuition fees at Austrian public universities (small student union fee)", allowance: "Monthly stipend of €1,050 (Master) or €1,150 (PhD)", travel: "Travel allowance of up to €1,200", insurance: "Health insurance coverage", housing: "Housing support through OeAD", other: "German language and cultural preparation course" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible countries (Egypt included)", age: "Under 35", education: "Bachelor's degree for Master, Master's for PhD", language: "German or English proficiency depending on the program", documents: ["Online application via OeAD portal", "CV", "Motivation letter", "Academic transcripts", "Recommendation letters (2)", "Language proficiency certificate", "Passport copy"] }),
    sourceUrl: "https://oead.at/en/",
    source: "MANUAL",
  },
  {
    nameEn: "University of Queensland — Destination Australia Scholarship",
    nameAr: "منحة جامعة كوينزلاند",
    country: "Australia",
    university: "University of Queensland",
    degree: "Bachelor / Master / PhD",
    deadline: new Date("2026-02-28T23:59:00Z"),
    flagUrl: "/images/flags/australia.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["BACHELOR", "MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ or TOEFL 85+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Australian government's Destination Australia scholarship supports international and domestic students to study at regional campuses like UQ.",
    benefits: JSON.stringify({ tuition: "Partial tuition fee coverage ($15,000 per year)", allowance: "Not provided", travel: "Not covered", housing: "Possible housing support", insurance: "Basic student insurance", other: "Settlement support and orientation" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities", age: "No strict age limit", education: "High school for Bachelor, relevant degree for postgraduate", language: "English proficiency (TOEFL 85+/IELTS 6.5+)", documents: ["Admission application to UQ", "Scholarship application form", "Personal statement", "Academic transcripts", "CV", "Recommendation letters"] }),
    sourceUrl: "https://scholarships.uq.edu.au/scholarships/destination-australia-program",
    source: "MANUAL",
  },
  {
    nameEn: "Clarendon Fund Scholarship (University of Oxford)",
    nameAr: "منحة كلارندن — أوكسفورد",
    country: "United Kingdom",
    university: "University of Oxford",
    degree: "Master / PhD",
    deadline: new Date("2026-01-10T23:59:00Z"),
    flagUrl: "/images/flags/uk.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine"],
    eligibleEducation: ["MASTER", "PHD"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: null,
    minimumGPA: 3.5,
    englishRequirement: "IELTS 7.0+ (varies by department)",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "high",
    requiredDocuments: ["RESEARCH_PROPOSAL", "PERSONAL_STATEMENT", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Clarendon Fund is a prestigious graduate scholarship at the University of Oxford, offering full funding for outstanding academic merit across all disciplines.",
    benefits: JSON.stringify({ tuition: "Full Oxford tuition fees (University Composition Fee)", allowance: "Annual living stipend of at least £19,237 (2025/26 rate)", travel: "Not covered", housing: "College accommodation included", insurance: "Health insurance (NHS surcharge covered)", other: "Access to Clarendon networking events, mentoring, and career development" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities (up to 140 new scholars/year)", age: "No age limit", education: "First-class or strong upper-second-class Bachelor's degree", language: "English proficiency (TOEFL 100+/IELTS 7.0+)", documents: ["Apply to an Oxford graduate program via the standard application", "Academic transcripts and degree certificates", "Personal statement", "CV/Resume", "Three recommendation letters", "Research proposal (for PhD programs)", "Writing sample (if required)"] }),
    sourceUrl: "https://www.ox.ac.uk/clarendon",
    source: "MANUAL",
  },
  {
    nameEn: "Danish Government Scholarship (University of Copenhagen)",
    nameAr: "منحة الحكومة الدنماركية",
    country: "Denmark",
    university: "Participating Danish Universities",
    degree: "Master",
    deadline: new Date("2026-03-01T23:59:00Z"),
    flagUrl: "/images/flags/denmark.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.5+ or TOEFL 88+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Danish government provides scholarships through Danish universities for highly qualified international students from outside the EU/EEA.",
    benefits: JSON.stringify({ tuition: "Full or partial tuition fee waiver", allowance: "Monthly living stipend (DKK 5,000-8,000)", travel: "Not covered", housing: "Housing assistance through the university", insurance: "Student health insurance included", other: "Free Danish language course, mentor program" }),
    requirements: JSON.stringify({ nationality: "Non-EU/EEA nationals from eligible countries", age: "No strict age limit", education: "Bachelor's degree in a relevant field", language: "English proficiency (TOEFL 88+/IELTS 6.5+)", documents: ["Apply for admission to the Danish university first", "Scholarship application (separate)", "Motivation letter", "CV", "Academic transcripts and diploma", "Proof of English proficiency", "Recommendation letters (1-2)"] }),
    sourceUrl: "https://studyindenmark.dk/",
    source: "MANUAL",
  },
  {
    nameEn: "University of Bologna Study Grant for International Students (Italy)",
    nameAr: "منحة جامعة بولونيا",
    country: "Italy",
    university: "University of Bologna",
    degree: "Bachelor / Master",
    deadline: new Date("2026-04-30T23:59:00Z"),
    flagUrl: "/images/flags/italy.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine", "Syria"],
    eligibleEducation: ["BACHELOR", "MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 30,
    minimumGPA: 3.0,
    englishRequirement: "IELTS 6.0+ or TOEFL 80+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "low",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "TRANSCRIPT"],
    description: "The University of Bologna offers study grants to outstanding international students for Bachelor's and Master's degree programs at one of the world's oldest universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee waiver", allowance: "€11,000-€16,000 per year based on income", travel: "Not covered", housing: "Housing assistance and discounts", insurance: "Health insurance coverage", other: "Free Italian language courses, free meals at university canteens" }),
    requirements: JSON.stringify({ nationality: "Open to all international students", age: "Under 30", education: "High school for Bachelor, Bachelor for Master", language: "English or Italian proficiency depending on program", documents: ["Online application for admission", "Separate grant application", "Academic transcripts and certificates", "Motivation letter", "CV/Resume", "Language proficiency certificate", "Income/financial documents (for needs-based portion)"] }),
    sourceUrl: "https://www.unibo.it/en/",
    source: "MANUAL",
  },
  {
    nameEn: "ARES Scholarship (Belgium)",
    nameAr: "منحة ARES البلجيكية",
    country: "Belgium",
    university: "Participating Belgian Universities (ARES network)",
    degree: "Master",
    deadline: new Date("2026-02-07T23:59:00Z"),
    flagUrl: "/images/flags/belgium.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Economics", "Law", "Political Science"],
    minimumAge: 18,
    maximumAge: 45,
    minimumGPA: 3.0,
    englishRequirement: "French B2+ or English B2+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The ARES scholarship supports international students from developing countries to pursue Master's programs in French-speaking Belgian universities.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Monthly living allowance of approximately €1,150", travel: "International travel costs covered one time", housing: "Housing allowance", insurance: "Health insurance covered", other: "Installation allowance of €1,000, visa costs, cultural activities" }),
    requirements: JSON.stringify({ nationality: "Open to citizens of eligible developing countries (Egypt included)", age: "Under 40 for most programs", education: "Bachelor's degree in a relevant field", language: "French B2 (most programs are in French) or English B2", documents: ["Online application", "Academic transcripts and diplomas", "Motivation letter specific to the field", "CV", "Recommendation letters (2)", "Proof of language proficiency", "Valid passport"] }),
    sourceUrl: "https://www.ares-ac.be/en/scholarships",
    source: "MANUAL",
  },
  {
    nameEn: "VLIR-UOS Scholarship (Belgium — Master)",
    nameAr: "منحة VLIR-UOS البلجيكية",
    country: "Belgium",
    university: "Flemish Universities (Ghent, KU Leuven, Antwerp, VUB, etc.)",
    degree: "Master",
    deadline: new Date("2026-02-01T23:59:00Z"),
    flagUrl: "/images/flags/belgium.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia", "Palestine"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Engineering", "Computer Science", "Environmental Science", "Economics", "Biology"],
    minimumAge: 18,
    maximumAge: 40,
    minimumGPA: 3.0,
    englishRequirement: "TOEFL 80+ or IELTS 6.5+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "VLIR-UOS offers scholarships for students from developing countries to follow an English-taught Master's program at a Flemish university in Belgium.",
    benefits: JSON.stringify({ tuition: "Full tuition fee coverage", allowance: "Monthly living allowance of €1,050", travel: "Round-trip airfare covered", housing: "Accommodation allowance (€100-150/month)", insurance: "Health and accident insurance", other: "Installation allowance of €500, visa costs, orientation program" }),
    requirements: JSON.stringify({ nationality: "Citizens of 31 eligible countries (Egypt included)", age: "Under 40", education: "Bachelor's degree in a relevant field", language: "English proficiency (TOEFL 80+/IELTS 6.5+)", documents: ["Online application", "Academic transcripts and diplomas", "Motivation letter", "CV", "Recommendation letters (2)", "Proof of English proficiency", "Valid passport"] }),
    sourceUrl: "https://www.vliruos.be/en/scholarships",
    source: "MANUAL",
  },
  {
    nameEn: "University of Geneva Excellence Master Fellowship (Switzerland)",
    nameAr: "منحة جامعة جنيف",
    country: "Switzerland",
    university: "University of Geneva",
    degree: "Master",
    deadline: new Date("2026-02-28T23:59:00Z"),
    flagUrl: "/images/flags/switzerland.svg",
    eligibleCountries: ["Egypt", "Saudi Arabia", "Jordan", "Lebanon", "Morocco", "Tunisia"],
    eligibleEducation: ["MASTER"],
    fieldOfStudy: ["Any"],
    minimumAge: 18,
    maximumAge: 35,
    minimumGPA: 3.3,
    englishRequirement: "TOEFL 90+ or IELTS 6.5+",
    requiresResearch: false,
    requiresWorkExp: false,
    applicationFee: null,
    competitionLevel: "medium",
    requiredDocuments: ["MOTIVATION_LETTER", "CV", "RECOMMENDATION_LETTER", "TRANSCRIPT"],
    description: "The Excellence Master Fellowships at the University of Geneva provide full funding for outstanding international students pursuing Master's degrees.",
    benefits: JSON.stringify({ tuition: "No tuition fees (CHF 500 enrollment fee/semester)", allowance: "Monthly stipend of CHF 1,600-CHF 2,000", travel: "Not covered", housing: "Housing assistance", insurance: "Health insurance partially covered", other: "Free access to sports and cultural activities, career mentoring" }),
    requirements: JSON.stringify({ nationality: "Open to all nationalities", age: "No strict age limit", education: "Excellent Bachelor's degree", language: "English or French proficiency (depending on program)", documents: ["Apply for admission to University of Geneva Master's program", "Separate scholarship application", "Motivation letter", "CV/Resume", "Academic transcripts", "Recommendation letters (2)", "Proof of language proficiency"] }),
    sourceUrl: "https://www.unige.ch/etudes/en/apply/scholarships/excellence-master-fellowships/",
    source: "MANUAL",
  },
];

async function main() {
  console.log("Seeding scholarships...");

  const stats = { created: 0, updated: 0, renamed: 0, unchanged: 0, keptFields: 0 };

  /**
   * One upsert for every source (curated + scraped), sharing the merge logic
   * from scripts/lib/scholarship-data.mjs (also used by the import CLI):
   *
   *  - Incoming text is normalised + mojibake-repaired at ingest time.
   *  - Match by nameEn first, then by sourceUrl (single match only) — a
   *    sourceUrl match with a different nameEn is treated as a safe rename.
   *  - Never overwrite a populated existing field (fill-empty only), so a
   *    re-seed can't clobber an operator's manual edits or enrichments.
   */
  async function applyRecord(input: ScholarshipInput | Prisma.ScholarshipCreateInput) {
    const incoming = normalizeRecord(input as unknown as ScholarshipLike);
    const nameEn = String(incoming.nameEn ?? "");

    let existing = await prisma.scholarship.findUnique({ where: { nameEn } });
    let matchKind: "exact" | "source-url" | "none" = existing ? "exact" : "none";

    if (!existing && incoming.sourceUrl) {
      const byUrl = await prisma.scholarship.findMany({
        where: { sourceUrl: String(incoming.sourceUrl) },
      });
      if (byUrl.length === 1) {
        existing = byUrl[0] ?? null;
        matchKind = "source-url";
      }
    }

    if (!existing) {
      await prisma.scholarship.create({
        data: incoming as unknown as Prisma.ScholarshipCreateInput,
      });
      stats.created += 1;
      return;
    }

    const merge = mergeScholarship(existing, incoming, { force: false });
    const data = merge.update as unknown as Prisma.ScholarshipUpdateInput;

    if (matchKind === "source-url" && existing.nameEn !== nameEn) {
      data.nameEn = nameEn;
      stats.renamed += 1;
    }

    if (Object.keys(merge.update).length === 0 && !data.nameEn) {
      stats.unchanged += 1;
      return;
    }

    await prisma.scholarship.update({ where: { id: existing.id }, data });
    stats.updated += 1;
    stats.keptFields += merge.kept.length;
  }

  for (const s of scholarships) await applyRecord(s);

  console.log(`Seeding ${scrapedScholarships.length} scraped scholarships...`);
  for (const s of scrapedScholarships) await applyRecord(s);

  const count = await prisma.scholarship.count();
  console.log(
    `Done. Total scholarships: ${count} ` +
      `(created=${stats.created}, updated=${stats.updated}, ` +
      `renamed=${stats.renamed}, unchanged=${stats.unchanged}, ` +
      `kept-conflicts=${stats.keptFields})`
  );
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error("Seed error:", error);
    await prisma.$disconnect();
    process.exit(1);
  });
