/**
 * Task 3B — synthetic matching personas (read-only audit fixture).
 *
 * All values are SYNTHETIC. No real user data. Each persona is deterministic
 * and labelled. Fields mirror the `MatchParams` shape consumed by
 * `matchScholarshipsToUser` (src/lib/scholarship-matcher.ts).
 */
import type { MatchParams } from "../../src/lib/scholarship-matcher";

export interface Persona {
  id: string;
  label: string;
  intent: string;
  profile: MatchParams;
}

/** Fixed synthetic birthdates so results are reproducible. */
const DOB = {
  age17: "2009-01-15",
  age20: "2006-03-10",
  age23: "2003-05-20",
  age24: "2002-07-01",
  age28: "1998-11-12",
  age30: "1996-02-25",
  age34: "1992-04-18",
  age40: "1986-08-09",
  age15: "2011-06-30",
};

export const personas: Persona[] = [
  {
    id: "P01",
    label: "Egyptian high-school → Bachelor (CS)",
    intent: "Basic bachelor applicant, likely eligible for broad programmes.",
    profile: {
      dateOfBirth: DOB.age17,
      country: "Egypt",
      educationLevel: "high-school",
      major: "Computer Science",
      targetDegree: "bachelor",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: 3.6,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P02",
    label: "Egyptian undergrad → Master (CS, strong GPA)",
    intent: "Common Egyptian applicant: good GPA, targeting master's.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Computer Science",
      targetDegree: "master",
      englishLevel: "ADVANCED",
      hasEnglishTest: "YES",
      budget: "NONE",
      gpa: 3.6,
      hasResearch: true,
      hasWorkExperience: false,
    },
  },
  {
    id: "P03",
    label: "Egyptian graduate → PhD (Engineering, research-heavy)",
    intent: "Research-focused PhD candidate with work experience.",
    profile: {
      dateOfBirth: DOB.age28,
      country: "Egypt",
      educationLevel: "master",
      major: "Engineering",
      targetDegree: "phd",
      englishLevel: "ADVANCED",
      hasEnglishTest: "YES",
      budget: "NONE",
      gpa: 3.5,
      hasResearch: true,
      hasWorkExperience: true,
    },
  },
  {
    id: "P04",
    label: "Saudi undergrad → Master (Business)",
    intent: "Gulf applicant; some scholarships are MENA-only, some 'All'.",
    profile: {
      dateOfBirth: DOB.age24,
      country: "Saudi Arabia",
      educationLevel: "bachelor",
      major: "Business Administration",
      targetDegree: "master",
      englishLevel: "ADVANCED",
      hasEnglishTest: "YES",
      budget: "MODERATE",
      gpa: 3.2,
      hasResearch: false,
      hasWorkExperience: true,
    },
  },
  {
    id: "P05",
    label: "Indian applicant (excluded by Arab/MENA-restricted scholarships)",
    intent: "Country not on several MENA-only lists — tests hard country exclusion.",
    profile: {
      dateOfBirth: DOB.age24,
      country: "India",
      educationLevel: "bachelor",
      major: "Engineering",
      targetDegree: "master",
      englishLevel: "ADVANCED",
      hasEnglishTest: "YES",
      budget: "NONE",
      gpa: 3.7,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P06",
    label: "Above-max-age applicant (40)",
    intent: "Exceeds maximumAge on the 4 scholarships that set an upper bound.",
    profile: {
      dateOfBirth: DOB.age40,
      country: "Egypt",
      educationLevel: "master",
      major: "Engineering",
      targetDegree: "phd",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: 3.0,
      hasResearch: true,
      hasWorkExperience: true,
    },
  },
  {
    id: "P07",
    label: "Below-min-age applicant (15)",
    intent: "Younger than the minimumAge on the 4 scholarships that set a bound.",
    profile: {
      dateOfBirth: DOB.age15,
      country: "Egypt",
      educationLevel: "high-school",
      major: "Science",
      targetDegree: "bachelor",
      englishLevel: "BEGINNER",
      hasEnglishTest: "PREFER_WITHOUT",
      budget: "NONE",
      gpa: null,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P08",
    label: "GPA below the single minimum (2.5 vs 3.0)",
    intent: "Below minimumGPA on the only scholarship that sets one.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Business Administration",
      targetDegree: "master",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: 2.5,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P09",
    label: "GPA above the single minimum (3.8)",
    intent: "Comfortably clears the 3.0 minimum on the same scholarship.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Business Administration",
      targetDegree: "master",
      englishLevel: "ADVANCED",
      hasEnglishTest: "YES",
      budget: "NONE",
      gpa: 3.8,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P10",
    label: "Wrong field (Chemistry vs Business/Human-Rights scholarships)",
    intent: "Field not on the 3 narrow field lists; all 'Any' scholarships unaffected.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Chemistry",
      targetDegree: "master",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: 3.4,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P11",
    label: "Correct field (Business student)",
    intent: "Matches the 3 business/human-rights-restricted scholarships exactly.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Business Administration",
      targetDegree: "master",
      englishLevel: "ADVANCED",
      hasEnglishTest: "YES",
      budget: "NONE",
      gpa: 3.4,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P12",
    label: "Missing GPA (null)",
    intent: "gpa unknown — tests missing-data handling for GPA.",
    profile: {
      dateOfBirth: DOB.age24,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Economics",
      targetDegree: "master",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: null,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P13",
    label: "Missing nationality (country = '')",
    intent: "country missing — tests country handling when the user value is empty.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "",
      educationLevel: "bachelor",
      major: "Engineering",
      targetDegree: "master",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: 3.0,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P14",
    label: "Fully-funded hunter, no English test wanted",
    intent: "Prefers no English test; ranks no-test scholarships up hard.",
    profile: {
      dateOfBirth: DOB.age20,
      country: "Egypt",
      educationLevel: "high-school",
      major: "Medicine",
      targetDegree: "bachelor",
      englishLevel: "BEGINNER",
      hasEnglishTest: "PREFER_WITHOUT",
      budget: "NONE",
      gpa: 3.9,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P15",
    label: "Broad applicant (Egyptian, bachelor, all levels)",
    intent: "Likely eligible for many scholarships at once — tests multi-match.",
    profile: {
      dateOfBirth: DOB.age20,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Computer Science",
      targetDegree: "bachelor",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "LIMITED",
      gpa: 3.3,
      hasResearch: false,
      hasWorkExperience: true,
    },
  },
  {
    id: "P16",
    label: "Exchange-program target (targetDegree=exchange)",
    intent: "targetDegree not in any eligibleEducation list — tests partial-match path.",
    profile: {
      dateOfBirth: DOB.age23,
      country: "Egypt",
      educationLevel: "bachelor",
      major: "Economics",
      targetDegree: "exchange",
      englishLevel: "INTERMEDIATE",
      hasEnglishTest: "WILLING",
      budget: "NONE",
      gpa: 3.2,
      hasResearch: false,
      hasWorkExperience: false,
    },
  },
  {
    id: "P17",
    label: "Legacy profile (no hasEnglishTest, englishLevel=ADVANCED)",
    intent: "Profiles created before hasEnglishTest existed — legacy branch.",
    profile: {
      dateOfBirth: DOB.age30,
      country: "Jordan",
      educationLevel: "master",
      major: "Political Science",
      targetDegree: "phd",
      englishLevel: "ADVANCED",
      hasEnglishTest: null,
      budget: "NONE",
      gpa: 3.4,
      hasResearch: true,
      hasWorkExperience: false,
    },
  },
];
