CREATE INDEX IF NOT EXISTS idx_countries_continent_id ON countries (continent_id);
CREATE INDEX IF NOT EXISTS idx_cities_country_id ON cities (country_id);
CREATE INDEX IF NOT EXISTS idx_campuses_university_id ON campuses (university_id);
CREATE INDEX IF NOT EXISTS idx_campuses_country_id ON campuses (country_id);
CREATE INDEX IF NOT EXISTS idx_campuses_city_id ON campuses (city_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_provider_id ON scholarships (provider_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_country_id ON scholarships (country_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_university_id ON scholarships (university_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_campus_id ON scholarships (campus_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_degree_level_id ON scholarships (degree_level_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_study_field_id ON scholarships (study_field_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_application_fee_currency_id ON scholarships (application_fee_currency_id);
CREATE INDEX IF NOT EXISTS idx_scholarships_verified_by ON scholarships (verified_by);
CREATE INDEX IF NOT EXISTS idx_scholarships_source_id ON scholarships (source_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_cycles_scholarship_id ON scholarship_cycles (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_benefits_scholarship_id ON scholarship_benefits (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_benefits_currency_id ON scholarship_benefits (currency_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_requirements_scholarship_id ON scholarship_requirements (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_documents_scholarship_id ON scholarship_documents (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_reviews_scholarship_id ON scholarship_reviews (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_reviews_user_id ON scholarship_reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_faqs_scholarship_id ON scholarship_faqs (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_gallery_scholarship_id ON scholarship_gallery (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_news_scholarship_id ON scholarship_news (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_blogs_author_id ON blogs (author_id);
CREATE INDEX IF NOT EXISTS idx_events_country_id ON events (country_id);
CREATE INDEX IF NOT EXISTS idx_events_city_id ON events (city_id);
CREATE INDEX IF NOT EXISTS idx_events_university_id ON events (university_id);
CREATE INDEX IF NOT EXISTS idx_users_country_id ON users (country_id);
CREATE INDEX IF NOT EXISTS idx_users_city_id ON users (city_id);
CREATE INDEX IF NOT EXISTS idx_users_language_id ON users (language_id);
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users (referred_by);
CREATE INDEX IF NOT EXISTS idx_user_profiles_nationality_country_id ON user_profiles (nationality_country_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_residence_country_id ON user_profiles (residence_country_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_current_degree_id ON user_profiles (current_degree_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_target_degree_id ON user_profiles (target_degree_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_major_field_id ON user_profiles (major_field_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_university_id ON user_profiles (university_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_budget_currency_id ON user_profiles (budget_currency_id);
CREATE INDEX IF NOT EXISTS idx_user_education_user_id ON user_education (user_id);
CREATE INDEX IF NOT EXISTS idx_user_education_degree_level_id ON user_education (degree_level_id);
CREATE INDEX IF NOT EXISTS idx_user_education_field_id ON user_education (field_id);
CREATE INDEX IF NOT EXISTS idx_user_education_country_id ON user_education (country_id);
CREATE INDEX IF NOT EXISTS idx_user_education_city_id ON user_education (city_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_user_id ON user_achievements (user_id);
CREATE INDEX IF NOT EXISTS idx_user_work_experience_user_id ON user_work_experience (user_id);
CREATE INDEX IF NOT EXISTS idx_user_work_experience_country_id ON user_work_experience (country_id);
CREATE INDEX IF NOT EXISTS idx_user_work_experience_city_id ON user_work_experience (city_id);
CREATE INDEX IF NOT EXISTS idx_user_volunteer_experience_user_id ON user_volunteer_experience (user_id);
CREATE INDEX IF NOT EXISTS idx_user_volunteer_experience_country_id ON user_volunteer_experience (country_id);
CREATE INDEX IF NOT EXISTS idx_user_research_experience_user_id ON user_research_experience (user_id);
CREATE INDEX IF NOT EXISTS idx_user_research_experience_field_id ON user_research_experience (field_id);
CREATE INDEX IF NOT EXISTS idx_user_finance_currency_id ON user_finance (currency_id);
CREATE INDEX IF NOT EXISTS idx_user_documents_user_id ON user_documents (user_id);
CREATE INDEX IF NOT EXISTS idx_user_documents_parent_document_id ON user_documents (parent_document_id);
CREATE INDEX IF NOT EXISTS idx_user_recommendation_letters_user_id ON user_recommendation_letters (user_id);
CREATE INDEX IF NOT EXISTS idx_user_essays_user_id ON user_essays (user_id);
CREATE INDEX IF NOT EXISTS idx_applications_user_id ON applications (user_id);
CREATE INDEX IF NOT EXISTS idx_applications_scholarship_id ON applications (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_applications_cycle_id ON applications (cycle_id);
CREATE INDEX IF NOT EXISTS idx_application_tasks_application_id ON application_tasks (application_id);
CREATE INDEX IF NOT EXISTS idx_application_tasks_stage_id ON application_tasks (stage_id);
CREATE INDEX IF NOT EXISTS idx_application_documents_application_id ON application_documents (application_id);
CREATE INDEX IF NOT EXISTS idx_application_documents_stage_id ON application_documents (stage_id);
CREATE INDEX IF NOT EXISTS idx_application_documents_user_document_id ON application_documents (user_document_id);
CREATE INDEX IF NOT EXISTS idx_application_documents_scholarship_document_id ON application_documents (scholarship_document_id);
CREATE INDEX IF NOT EXISTS idx_saved_scholarships_scholarship_id ON saved_scholarships (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_favorites_scholarship_id ON favorites (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_ai_chats_user_id ON ai_chats (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_messages_chat_id ON ai_chat_messages (chat_id);
CREATE INDEX IF NOT EXISTS idx_ai_reviews_user_id ON ai_reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_reviews_user_document_id ON ai_reviews (user_document_id);
CREATE INDEX IF NOT EXISTS idx_ai_reviews_application_document_id ON ai_reviews (application_document_id);
CREATE INDEX IF NOT EXISTS idx_ai_reports_user_id ON ai_reports (user_id);
CREATE INDEX IF NOT EXISTS idx_acceptance_predictions_scholarship_id ON acceptance_predictions (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_ai_matching_jobs_user_id ON ai_matching_jobs (user_id);
CREATE INDEX IF NOT EXISTS idx_search_history_user_id ON search_history (user_id);
CREATE INDEX IF NOT EXISTS idx_search_history_clicked_scholarship_id ON search_history (clicked_scholarship_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_emails_user_id ON emails (user_id);
CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments (user_id);
CREATE INDEX IF NOT EXISTS idx_payments_currency_id ON payments (currency_id);
CREATE INDEX IF NOT EXISTS idx_payments_reviewed_by ON payments (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_sources_country_id ON sources (country_id);
CREATE INDEX IF NOT EXISTS idx_sources_provider_id ON sources (provider_id);
CREATE INDEX IF NOT EXISTS idx_import_batches_source_id ON import_batches (source_id);
CREATE INDEX IF NOT EXISTS idx_import_batches_created_by ON import_batches (created_by);
CREATE INDEX IF NOT EXISTS idx_import_queue_items_batch_id ON import_queue_items (batch_id);
CREATE INDEX IF NOT EXISTS idx_import_queue_items_scholarship_id ON import_queue_items (scholarship_id);
CREATE INDEX IF NOT EXISTS idx_scholarship_versions_created_by ON scholarship_versions (created_by);
CREATE INDEX IF NOT EXISTS idx_scholarship_change_logs_changed_by ON scholarship_change_logs (changed_by);
CREATE INDEX IF NOT EXISTS idx_duplicates_resolved_by ON duplicates (resolved_by);
CREATE INDEX IF NOT EXISTS idx_verification_queue_reviewer_id ON verification_queue (reviewer_id);

CREATE INDEX IF NOT EXISTS idx_scholarships_search_vector_gin ON scholarships USING gin (search_vector);
CREATE INDEX IF NOT EXISTS idx_scholarships_title_trgm ON scholarships USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_scholarships_title_ar_trgm ON scholarships USING gin (title_ar gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_scholarships_slug_trgm ON scholarships USING gin (slug gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_universities_name_trgm ON universities USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_universities_name_ar_trgm ON universities USING gin (name_ar gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_providers_name_trgm ON providers USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_ai_embeddings_embedding_hnsw ON ai_embeddings USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON analytics_events (created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event_name_created_at ON analytics_events (event_name, created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_user_id ON analytics_events (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id_created_at ON audit_logs (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type_entity_id ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id_created_at ON activity_logs (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_activity_logs_entity_type_entity_id ON activity_logs (entity_type, entity_id);

-- FK-supporting indexes (validator-required single-column coverage)
CREATE INDEX IF NOT EXISTS idx_countries_currency_id ON countries (currency_id);
CREATE INDEX IF NOT EXISTS idx_study_fields_parent_id ON study_fields (parent_id);
CREATE INDEX IF NOT EXISTS idx_universities_city_id ON universities (city_id);
CREATE INDEX IF NOT EXISTS idx_universities_verified_by ON universities (verified_by);
CREATE INDEX IF NOT EXISTS idx_providers_country_id ON providers (country_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_target_country_id ON user_profiles (target_country_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON activity_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_app_settings_updated_by ON app_settings (updated_by);